// Human-to-cat phrase book: what the person was saying TO their cat.
// CAT_PHRASES[meowCount]["short" | "long"]. "short" = normal meows,
// "long" = drawn-out meows (more dramatic). 6 means 6 or more.
window.CAT_PHRASES = {
 "1": {
  "short": [
   "Hey cat.",
   "Hi kitty.",
   "Dinner time!",
   "Good kitty.",
   "Hello, fluffball.",
   "Come here.",
   "Treat time?",
   "Nap time.",
   "Sweet dreams.",
   "Good morning.",
   "Good night.",
   "Nice stretch.",
   "Who's there?",
   "Off, please.",
   "Down, kitty.",
   "Tuna tonight.",
   "Fish?",
   "Snack time.",
   "Breakfast time!",
   "Lunch time.",
   "Belly rubs?",
   "Chin scratch?",
   "Little floof.",
   "Mister Whiskers.",
   "Gentle paws.",
   "No biting.",
   "No scratching.",
   "Not the couch.",
   "Not the plant.",
   "Drop it.",
   "Leave it.",
   "Stay.",
   "Sit.",
   "Wait.",
   "Good job.",
   "Nice catch.",
   "Pounce!",
   "Get it!",
   "Laser time!",
   "Box time?",
   "In the box?",
   "Vet day.",
   "Carrier time.",
   "It's okay.",
   "You're safe.",
   "Easy now.",
   "Shh, kitty.",
   "Quiet, please.",
   "Too early.",
   "Back to bed.",
   "Stop meowing.",
   "Hi, sweetie.",
   "Hey, buddy.",
   "Hey there.",
   "Morning, sunshine.",
   "Evening, floof.",
   "Welcome home.",
   "Where'd you go?",
   "Found you!",
   "Peekaboo!",
   "Boop.",
   "Bless you.",
   "Eww, hairball.",
   "Clean box.",
   "Fresh water.",
   "Eat up.",
   "Slow down.",
   "That's mine.",
   "Not yours.",
   "Share?",
   "Scoot over.",
   "Move, please.",
   "My pillow.",
   "Keyboard, no!",
   "Off the table.",
   "Off the counter.",
   "Nope.",
   "Absolutely not.",
   "Really, cat?",
   "Why?",
   "Uh oh.",
   "Oops.",
   "Sorry, kitty.",
   "Thank you.",
   "Thanks, buddy.",
   "Aw, a gift?",
   "Love you.",
   "Missed you.",
   "Cuddle time.",
   "Lap's open.",
   "Up you go.",
   "Down you go.",
   "Purr for me.",
   "Pretty kitty.",
   "Handsome boy.",
   "Pretty girl.",
   "Silly cat.",
   "Goofball.",
   "Tiny tiger.",
   "Brave hunter.",
   "Cutie.",
   "Sweet pea.",
   "Bedtime.",
   "Lights out.",
   "Drink up.",
   "Chew, please.",
   "Nose boop.",
   "Such purrs.",
   "Well done.",
   "Jump!"
  ],
  "long": [
   "Noooo!",
   "Kittyyyy!",
   "Heeey, kitty!",
   "Hiii, baby!",
   "Dinnerrrr!",
   "Treeeats!",
   "Tunaaa!",
   "But whyyy?",
   "Pleeease!",
   "Stoppp!",
   "Get DOWN!",
   "Not AGAIN!",
   "Oh my GOSH!",
   "Awww, kitty!",
   "Soooo cute!",
   "My baaaby!",
   "Snuggle meee!",
   "Come baaack!",
   "Don't gooo!",
   "I'm hooome!",
   "Miss meee?",
   "NOT the curtains!",
   "Not the TREE!",
   "The vacuum?!",
   "Nooo, hairball!",
   "Ewww, gross!",
   "My MUG!",
   "My keyboard!",
   "My laptop!",
   "My SOCKS!",
   "Put it DOWN!",
   "Drop it NOW!",
   "Waaait, kitty!",
   "Heeelp!",
   "Whaaat?!",
   "Seriously?!",
   "Unbelievable!",
   "Oh, come ON!",
   "It's 3AM!",
   "Go to SLEEP!",
   "Zoomies AGAIN?!",
   "Sooo fluffy!",
   "Fluffballll!",
   "Teeny flooof!",
   "Whiiiskers, NO!",
   "Precious angel!",
   "Gorgeous baby!",
   "Beautiful kitty!",
   "Perfect kitty!",
   "Best cat EVER!",
   "Love you SO!",
   "Smoochies!",
   "Tummy rubs?!",
   "Chin scratchies!",
   "Squishy face!",
   "Toe beans!",
   "Look at youuu!",
   "Aww, the box!",
   "Bath tiiime!",
   "Vet tiiime!",
   "Sorryyy!",
   "Forgive meee!",
   "Pretty pleeease!",
   "The DOG?!",
   "Leave him ALONE!",
   "Stop bitinggg!",
   "OWWW!",
   "My HAND!",
   "Not my plant!",
   "The couch?! Nooo!",
   "Such a baby!",
   "Grumpy face!",
   "A dead MOUSE?!",
   "Oh, sweetie...",
   "Baby, NO!",
   "Spit it OUT!",
   "Not my dinner!",
   "Shhhhh!",
   "Mercy!",
   "Enough!",
   "I give up!",
   "You WIN!",
   "Fine, have it!",
   "Okay, OKAY!",
   "Five more minutes!",
   "Nom nom nom!",
   "Starving, huh?!",
   "Sooo dramatic!",
   "Drama queen!",
   "Rise and shiiine!",
   "Wake uuup!",
   "Nighty nighty!",
   "Sleepy babyyy!",
   "Bestest kitty!",
   "Clever kitty!",
   "Genius cat!",
   "The red DOT!",
   "Get the dot!",
   "What a GIFT!",
   "Don't eat that!",
   "Hungry, baby?!",
   "Ouchie!",
   "Stop yelling!",
   "Kisses!",
   "Brekkie?!",
   "Huge yawn!",
   "That's the FISH!",
   "The SINK?!",
   "Get OFF!",
   "Too cuuute!"
  ]
 },
 "2": {
  "short": [
   "Want a treat?",
   "Get off the counter.",
   "Who's a good kitty?",
   "Can I get you fish?",
   "Do you want some tuna?",
   "Time for dinner, kitty.",
   "Come get your breakfast.",
   "Here's some fresh water.",
   "Want a belly rub?",
   "Let me scratch your chin.",
   "Are you taking a nap?",
   "Nice spot you found.",
   "Look, the laser pointer!",
   "Catch the red dot.",
   "Do you like your box?",
   "We're going to the vet.",
   "Into the carrier, please.",
   "It's just the vacuum.",
   "Please get off my keyboard.",
   "Off the table, please.",
   "Why are you awake?",
   "It's three in the morning.",
   "Please use the litter box.",
   "I cleaned your litter box.",
   "Another hairball, buddy?",
   "Leave the tree alone.",
   "Don't climb the Christmas tree.",
   "Be nice to the dog.",
   "The dog is friendly.",
   "Is that a gift?",
   "Thank you for the mouse.",
   "I don't need a bird.",
   "Can I use my laptop?",
   "You're sitting on my work.",
   "Hello, mister whiskers.",
   "Hi there, little floof.",
   "Good morning, fluffball.",
   "Did you sleep well?",
   "What are you looking at?",
   "Do you see a bird?",
   "Want to play?",
   "Where's your toy mouse?",
   "Let's brush your fur.",
   "Hold still for me.",
   "Just a quick nail trim.",
   "You smell nice today.",
   "Your fur is so soft.",
   "I love your little paws.",
   "You have pretty eyes.",
   "Stop scratching the couch.",
   "Use your scratching post.",
   "Get out of the sink.",
   "That's not your food.",
   "That's my sandwich, buddy.",
   "Please don't lick that.",
   "Stop chewing the cord.",
   "Leave the plants alone.",
   "Yes, I'm in here.",
   "I'll be right back.",
   "I missed you today.",
   "How was your day?",
   "I'm home, kitty.",
   "Were you a good cat?",
   "Who made this mess?",
   "Did you knock this over?",
   "Please stop knocking things over.",
   "Be gentle with me.",
   "Easy with the claws.",
   "No biting my toes.",
   "Come sit on my lap.",
   "Are you comfy there?",
   "Scoot over a little.",
   "That's my pillow, cat.",
   "Can I have some blanket?",
   "You're warm and cozy.",
   "Go back to sleep.",
   "Time for bed, kitty.",
   "Let's cuddle on the couch.",
   "Want some chicken?",
   "Just a little bit.",
   "Dinner is almost ready.",
   "Your bowl isn't empty.",
   "You just ate, silly.",
   "I know you're hungry.",
   "Patience, little one.",
   "You're such a sweetheart.",
   "What a handsome boy.",
   "What a pretty girl.",
   "You're my best friend.",
   "I got you a present.",
   "Here's a new toy.",
   "Try the new bed.",
   "Want to go outside?",
   "Look at that squirrel.",
   "Stay away from the door.",
   "Please stop yelling at me.",
   "Why are you meowing?",
   "What do you need?",
   "Show me what's wrong.",
   "You're okay, sweetie.",
   "Let's take your medicine.",
   "Good job at the vet.",
   "Stop staring at me.",
   "Did you just sneeze?",
   "Is someone at the window?",
   "Fetch the toy.",
   "You picked the box, huh.",
   "Blink slowly back at me.",
   "Stop attacking my feet.",
   "The vacuum won't hurt you."
  ],
  "long": [
   "Nooo, not the curtains!",
   "Pleeease, not the keyboard!",
   "Who's the cutest kitty EVER?",
   "Not the Christmas tree AGAIN!",
   "Why are you like thisss?",
   "It's THREE A.M., kitty!",
   "Pleeease stop the zoomies!",
   "Nooo, not my mug!",
   "Stop knocking things OVER!",
   "The counter is OFF-LIMITS!",
   "Don't you DARE, kitty!",
   "I love you SO much!",
   "You're the best kitty EVER!",
   "Look at your tiny beans!",
   "Oh my gosh, SO fluffy!",
   "Whyyy did you bring this?",
   "A MOUSE? In the HOUSE?",
   "Pleeease stop biting me!",
   "My HAND is not food!",
   "Relax, it's the vacuuum!",
   "The vacuum won't EAT you!",
   "The vet is NOT scary!",
   "Come out from under there!",
   "Pleeease get in the carrier!",
   "Stop hiding, you silly baby!",
   "Not ANOTHER hairball!",
   "Nooo, not on the rug!",
   "Pleeease, the litter BOX!",
   "Leave the dog ALONE!",
   "Stop swatting the dog!",
   "My laptop isn't a BED!",
   "Pleeease move, I'm working!",
   "You got me a gift?!",
   "Awww, you missed me!",
   "I missed you SOOO much!",
   "Come here, my little floof!",
   "Who's my precious fluffball?",
   "Mister Whiskers, you're PERFECT!",
   "Give me the belly!",
   "Chin scratches for my baaaby!",
   "Tuuuna for my baby!",
   "You want the fishhh?!",
   "Dinner is COMING, I promise!",
   "I JUST fed you!",
   "You're NOT starving, drama queen!",
   "Stop screaming at the bowl!",
   "Five more minutes, pleeease!",
   "Let me sleeep, kitty!",
   "Why the 3AM zoomies?!",
   "You broke my FAVORITE mug!",
   "That was my DINNER!",
   "Not my SANDWICH!",
   "Out of the bathtub, NOW!",
   "Don't eat the tinsel!",
   "The ornaments are NOT toys!",
   "Get the laser, GET IT!",
   "The dot, the DOOOT!",
   "You caught it! GOOD JOB!",
   "You LOVE that box!",
   "I bought you a BED!",
   "Don't give me that LOOK!",
   "Pleeease stop staring at me!",
   "Oh, you're SO dramatic!",
   "Such a BIG baby!",
   "Who's my sleepy wittle baby?",
   "Snuggle with meee, pleeease!",
   "Don't leave meee, kitty!",
   "Come back, I'm SORRY!",
   "I'm sorry about the bath!",
   "Forgive me for the vet!",
   "Not the good couch!",
   "Those were NEW curtains!",
   "My plants are NOT salad!",
   "Stop chewing my HAIR!",
   "OWWW, your claws!",
   "Gentle paws, pleeease!",
   "Kitty, get DOWN from there!",
   "How are you UP there?!",
   "You're STUCK again?!",
   "Hold on, I'm COMING!",
   "Everything's on the FLOOR!",
   "Who ate the butter?!",
   "You drank my WATER?!",
   "Pleeease, just ONE cuddle!",
   "Let me kiss your head!",
   "Look at that FACE!",
   "Your little nose, AWWW!",
   "Squish squish squish!",
   "Stop sitting on my BOOK!",
   "Get off my homework!",
   "You're on my FACE, kitty!",
   "Stop licking my NOSE!",
   "Good MORNING, sunshine kitty!",
   "Where did you GOOO?",
   "I've been looking EVERYWHERE!",
   "You're in the DRYER?!",
   "The fridge is NOT yours!",
   "No ice cream for kitties!",
   "Bird TV is ON!",
   "That squirrel is TAUNTING you!",
   "You're the BRAVEST hunter!",
   "My tiny little TIGER!",
   "Twenty dollar bed, IGNORED!",
   "Nooo, not the dog's bowl!",
   "Stop the yowling, pleeease!",
   "Sooo many hairballs!",
   "Hisss at the vacuum, huh?",
   "Wake me up LATER!",
   "Stop pawing my FACE!",
   "Pleeease, not on the laptop!"
  ]
 },
 "3": {
  "short": [
   "Can I get you a fish?",
   "Who wants some tuna?",
   "Time for dinner, kitty.",
   "Want a chin scratch?",
   "Come here, little floof.",
   "Are you hungry again?",
   "Good morning, mister whiskers.",
   "Off the counter, please.",
   "Who's a good kitty?",
   "Want to chase the laser?",
   "Is that your new box?",
   "Nap time, fluffball.",
   "Did you eat your breakfast?",
   "Let's clean the litter box.",
   "You look very comfy.",
   "Get off my keyboard.",
   "What did you bring me?",
   "The vacuum is coming out.",
   "Be nice to the dog.",
   "Leave the tree alone.",
   "Do you want a treat?",
   "Come sit on my lap.",
   "Where are you hiding?",
   "That's my chair, buddy.",
   "You're so soft today.",
   "Stop chewing the cable.",
   "Let me pet you.",
   "How was your nap?",
   "Here's your fresh water.",
   "We're going to the vet.",
   "Into the carrier, sweetie.",
   "Are you purring at me?",
   "Hello, my little bean.",
   "Don't scratch the couch.",
   "Who's hungry for salmon?",
   "Want to play fetch?",
   "Nice stretch, kitty.",
   "You smell like sunshine.",
   "Is the bird outside?",
   "Stop staring at me.",
   "Here comes the feather toy.",
   "Paws off my sandwich.",
   "Do you have a hairball?",
   "Your bowl is full.",
   "Sweet dreams, fluffball.",
   "Please use the scratching post.",
   "Look, a cardboard box!",
   "Did you knock that over?",
   "Who's making biscuits?",
   "Let's brush your fur.",
   "What a handsome boy.",
   "What a pretty girl.",
   "Want some chicken?",
   "That's not your food.",
   "Get down from there.",
   "Say hi to grandma.",
   "Mind your tail, buddy.",
   "You're in the sink again?",
   "Thanks for the mouse.",
   "Stay out of the closet.",
   "Welcome home, kitty.",
   "Is it breakfast time already?",
   "I'm back, little floof.",
   "Let's trim your claws.",
   "Found your jingle ball.",
   "You sleep so much.",
   "Move over, please.",
   "Hop up on the bed.",
   "Gentle paws, please.",
   "No biting, mister.",
   "Do you like the sunbeam?",
   "The dog won't hurt you.",
   "Look at those toe beans.",
   "Tummy rub? Just kidding.",
   "You want the window open?",
   "Out of the laundry basket.",
   "Your catnip mouse arrived.",
   "Can I have my pillow?",
   "Who ate the houseplant?",
   "Have some kibble, sweetie.",
   "You're my best friend.",
   "I love your whiskers.",
   "Shh, the baby's sleeping.",
   "Wanna watch the birds?",
   "It's just the doorbell.",
   "Let me see your paw.",
   "Are you stuck up there?",
   "Don't eat the ribbon.",
   "Quit batting my pen.",
   "Is the heater warm?",
   "You're a little loaf.",
   "Here, kitty kitty.",
   "Tail out of my coffee.",
   "Why the side-eye?",
   "Your blanket is washed.",
   "Snack time, mister whiskers.",
   "Stop meowing at the fridge.",
   "Please drink some water.",
   "Did the vacuum scare you?",
   "Nice pounce, tiger.",
   "Put the sock down.",
   "Out of the dishwasher, please.",
   "Is that a new trick?",
   "You're getting a bit chunky.",
   "Time to take your pill.",
   "I made your bed.",
   "Guard the house, okay?",
   "Your favorite show is on.",
   "Who left this hairball?",
   "Your tuna is served."
  ],
  "long": [
   "Nooo, not the new curtains!",
   "Who's the cutest kitty EVER?",
   "Pleeease get off the counter!",
   "Whyyy is it 3am?",
   "I love you SO much!",
   "Not the laptop agaaain!",
   "My mug! My poor mug!",
   "You're the fluffiest floof EVER!",
   "Nooo, don't throw up there!",
   "Sooo many zoomies tonight!",
   "Stop screaming at the door!",
   "Pleeease let me sleep!",
   "Oh my gosh, those toe beans!",
   "Who's my baaaby?",
   "Not the Christmas tree AGAIN!",
   "It's just the vacuum, sweetie!",
   "You brought me a WHAT?",
   "Come baaack, little floof!",
   "Why is the dog crying?",
   "Your belly is SO fluffy!",
   "Get out of the tree!",
   "That's a HAIRBALL on my rug!",
   "Stop biting my toes!",
   "My keyboard! My email!",
   "Nooo, the vet isn't scary!",
   "Pretty pleeease come here!",
   "Is that a LIVE mouse?!",
   "The treats are coming, promise!",
   "Mister whiskers, you're PERFECT!",
   "Ugh, the litter box AGAIN?",
   "Oh no, my houseplant!",
   "Stop knocking stuff OVER!",
   "Why are you SO heavy?",
   "Kittyyy, where did you go?",
   "You're squishing my face!",
   "That was my DINNER!",
   "Gimme kisses, fluffball!",
   "Look at that little FACE!",
   "Nooo, not in the bathtub!",
   "Who's a precious angel? You!",
   "Stop yelling, I'm coming!",
   "Fine, FINE, here's more tuna!",
   "Not the toilet paper!",
   "Your fur is EVERYWHERE!",
   "Get off my HOMEWORK!",
   "I missed you SO much!",
   "Please stop the midnight parkour!",
   "Awww, you fell asleep!",
   "No no NO, not the sofa!",
   "Are you seriously hungry AGAIN?",
   "Ow, ow, claws, OW!",
   "The laser is GONE, sorry!",
   "That box is TINY, buddy!",
   "Don't leave me, kitty!",
   "Why do you HATE the vacuum?",
   "Don't eat the tinsel!",
   "Put the ornament BACK!",
   "The dog is your FRIEND!",
   "Stop chasing your tail, silly!",
   "I'm SO sorry about the bath!",
   "Awww, a gift for me?",
   "Please, not another dead bug!",
   "You're the BEST kitty ever!",
   "Wake me up at SEVEN!",
   "My sandwich! You thief!",
   "Stop pawing my face, pleeease!",
   "So much FLUFF, oh my!",
   "You're a little DIVA!",
   "Pleeease just one cuddle!",
   "You CANNOT go outside!",
   "Awww, you're making biscuits!",
   "My goodness, what a BIG yawn!",
   "Nooo, that's hot soup!",
   "Come snuggle, my sweet angel!",
   "Stop hissing at the dog!",
   "Not my new SHOES!",
   "Get out of the fridge!",
   "Oh, you tiny little MONSTER!",
   "That's not a scratching post!",
   "You broke ANOTHER glass?",
   "Come down off the roof!",
   "Your breath smells like TUNA!",
   "Sooo proud of you, kitty!",
   "Not my freshly folded laundry!",
   "Leave the goldfish ALONE!",
   "Mommy loves you SO much!",
   "Don't give me those eyes!",
   "The food bowl isn't EMPTY!",
   "Why the drama, fluffball?",
   "Stop, that's my PHONE!",
   "How are you SO cute?",
   "Quit meowing at the WALL!",
   "Not in the flour!",
   "Where did you find GLITTER?",
   "Stop drinking from my glass!",
   "Oh no, the yarn!",
   "Who's got the chubbiest cheeks?",
   "You're SUCH a goofball!",
   "Nooo, don't sit on the pizza!",
   "The couch is NOT yours!",
   "You're shedding on my SUIT!",
   "I'm on a Zoom call!",
   "Stop licking the plastic bag!",
   "You're heavier than a BRICK!",
   "How'd you get up THERE?",
   "Pleeease take your medicine!",
   "Oh, my sweet little meatball!",
   "Don't jump, you'll FALL!",
   "I didn't step on you, promise!",
   "Eww, not on my PILLOW!"
  ]
 },
 "4": {
  "short": [
   "Please stop knocking my mug over.",
   "Why are you sitting on my laptop?",
   "Would you like some salmon for dinner?",
   "Let's get you a nice chin scratch.",
   "I'll fill your water bowl right now.",
   "Do you want to play with the laser?",
   "Your new scratching post arrived today.",
   "Please don't walk across my keyboard.",
   "Come on, kitty, it's time for bed.",
   "I cleaned the litter box for you.",
   "We have a vet appointment on Tuesday.",
   "The vacuum won't hurt you, I promise.",
   "Can you please get off the counter?",
   "Thank you for the lovely dead moth.",
   "The dog just wants to be friends.",
   "Let's leave the Christmas tree alone this year.",
   "Do you want the big box or small?",
   "You can nap on my lap, little floof.",
   "How about a belly rub? Just one?",
   "I saved you some chicken from dinner.",
   "Please don't wake me up at 3am.",
   "Would you like to sit in the sunbeam?",
   "Your fur is getting all over my sweater.",
   "I think you have a hairball coming.",
   "Good morning, did you sleep well, fluffball?",
   "Let me brush out those knots gently.",
   "Why do you always sit in boxes?",
   "Please stop drinking out of my glass.",
   "Mister whiskers, your breakfast is ready.",
   "I know it's raining, you can't go out.",
   "Let's watch the birds from the window.",
   "That plant is not for eating, sweetie.",
   "You're welcome to share my pillow tonight.",
   "I bought you a brand new toy mouse.",
   "Please stop pushing things off the table.",
   "Do you want some tuna with your kibble?",
   "It's okay, the doorbell is just the mailman.",
   "Hop in the carrier, it's vet day.",
   "Can I have my chair back, please?",
   "You've been such a good kitty today.",
   "Let's trim your claws before they snag.",
   "The heating pad is on your bed.",
   "Why do you ignore your expensive cat bed?",
   "Stop chasing your brother around the house.",
   "I'll be home from work by six.",
   "Your grandma sent you a catnip banana.",
   "Is that my hair tie under the fridge?",
   "Please let me finish typing this email.",
   "I see you hiding behind the curtain.",
   "Your tail keeps getting in my soup.",
   "Come here and give me a head bump.",
   "Please don't eat the tinsel this time.",
   "We're moving your food bowl upstairs.",
   "The laser dot is gone now, sorry.",
   "You smell like the neighbor's garden again.",
   "Would you like the window seat today?",
   "Let's get your collar on, pretty girl.",
   "I love how you make little biscuits.",
   "You don't need to guard the bathroom door.",
   "Why did you bring a leaf inside?",
   "Please stop licking the shower curtain.",
   "You have the softest ears in town.",
   "That's my spot on the couch, buddy.",
   "I'm going to vacuum, you might hide.",
   "Look, I found your favorite jingle ball.",
   "Let's weigh you, you've gotten a bit round.",
   "The dog is on a walk, relax.",
   "Can you not sleep on my face?",
   "Your dinner is in five more minutes.",
   "Here's a little scratch behind the ears.",
   "Is the washing machine too loud for you?",
   "We should practice going in the carrier.",
   "Why is your paw in my cereal?",
   "You can have one more treat, fluffball.",
   "Your water fountain needs a new filter.",
   "Did you really eat a rubber band?",
   "I promise the cucumber isn't a snake.",
   "Please be polite when the guests arrive.",
   "Let's sit together and watch a movie.",
   "Stop batting the pens off my desk.",
   "How did you get into the pantry?",
   "Tell me about your big day, kitty.",
   "You look very regal on that shelf.",
   "I'm making tuna sandwiches, so don't beg.",
   "Your cat tree is finally put together.",
   "Please don't chew on the phone charger.",
   "That's a sock, not a mouse, silly.",
   "You're allowed on the bed tonight, okay?",
   "Stop sitting on the newspaper I'm reading.",
   "Want me to open the balcony door?",
   "I left the closet open for you.",
   "Your little nose is so pink today.",
   "Why do you only love the cheap toys?",
   "Gently, please, those are my fingers.",
   "Let's put on your little bow tie.",
   "We have a new baby coming home soon.",
   "I'll share a bit of my salmon.",
   "It's only thunder, you're safe with me.",
   "Please stop yelling at the pigeons outside.",
   "You fit perfectly in that shoebox.",
   "Stop stealing the dog's chew toy, please.",
   "I think it's time for your flea treatment.",
   "Did you just sneeze on my notebook?",
   "Your whiskers are tickling my cheek.",
   "Let me get the feather wand out.",
   "You're such a lovely little companion.",
   "Come get a kiss on the forehead.",
   "Can we try sleeping past five tomorrow?",
   "No, you may not have my pizza.",
   "Please share the blanket with me tonight."
  ],
  "long": [
   "Who's the cutest kitty in the WHOLE world?",
   "Nooo, please not the brand new curtains!",
   "Why are you doing zoomies at 3am?!",
   "I will give you ALL the tuna!",
   "Pleeease stop screaming, breakfast is coming!",
   "You threw up on my NEW rug?!",
   "Nooo, don't knock the Christmas tree over!",
   "Oh my goodness, you're the fluffiest fluffball EVER!",
   "Why must you sit on my LAPTOP?!",
   "I'm on a call, get OFF the keyboard!",
   "Pleeease, just one belly rub, I beg you!",
   "You brought me a WHOLE bird?! Why?!",
   "Nooo, the vet is not THAT bad!",
   "I love you more than ANYTHING, kitty!",
   "Stop attacking the vacuum, it's not ALIVE!",
   "Who ate the ENTIRE plate of shrimp?!",
   "Come down from the curtain rod RIGHT NOW!",
   "My poor mug, it was my FAVORITE!",
   "Please, PLEASE use the litter box, not the plant!",
   "You are the most beautiful creature ALIVE!",
   "Why is there a hairball in my SHOE?!",
   "Stop chasing the dog, he's TERRIFIED of you!",
   "Pleeease let me sleep for five more minutes!",
   "Oh no, you're stuck in the box AGAIN!",
   "Mister whiskers, you are SO handsome today!",
   "Nooo, the laser is not a bug!",
   "Give me those squishy little toe beans NOW!",
   "I leave for ONE hour and this happens?!",
   "You can't be hungry, you JUST ate!",
   "Awww, did you miss me, my precious baby?",
   "Who taught you to open the CUPBOARDS?!",
   "Please stop stealing my HAIR TIES, you thief!",
   "Nooo, don't drink out of the toilet!",
   "How are you SO soft and SO perfect?!",
   "That's the third glass this WEEK, kitty!",
   "My homework is NOT your bed, fluffball!",
   "Pleeease come out from under the bed!",
   "I'm SO sorry I stepped on your tail!",
   "You're the best little floof in the UNIVERSE!",
   "Why do you scream at the WALL every night?!",
   "Not the ornaments! Those were GRANDMA'S!",
   "Stop biting my ankles, I'm WALKING here!",
   "You ate the ribbon AGAIN? Oh, sweetie!",
   "Get out of the dryer, you silly goose!",
   "Wait, WHERE did you get that sock?!",
   "Who's a squishy little muffin? YOU are!",
   "Nooo, not ON the freshly folded laundry!",
   "The dog is NOT your personal bed, kitty!",
   "Oh my gosh, look at your sleepy little face!",
   "Pleeease stop meowing, the treats are RIGHT here!",
   "You are NOT allowed on the stove, EVER!",
   "Why do you hate the carrier SO much?!",
   "Fifty-dollar bed and you pick the BOX?!",
   "My sandwich! You licked my ENTIRE sandwich!",
   "Please don't push my phone off the table!",
   "Kittyyy, come back, I have your FAVORITE treat!",
   "Stop pawing at my face at FIVE AM!",
   "Nooo, that's my brand new cashmere sweater!",
   "Your purring is the BEST sound in the world!",
   "You are a tiny FURRY tornado, aren't you?!",
   "Stop licking the butter, that's GROSS, sweetie!",
   "Who unrolled the ENTIRE roll of toilet paper?!",
   "I can't believe you caught a REAL mouse!",
   "Pleeease stop hissing at your own reflection!",
   "You're getting fur all over my BLACK pants!",
   "Awww, look at you snoozing in the sunbeam!",
   "Get your tail out of my coffee, pleeease!",
   "That tiny box can't POSSIBLY fit you!",
   "The fish tank is NOT a buffet, mister!",
   "How dare you look so cute while misbehaving?!",
   "Oh no, you knocked the plant over AGAIN!",
   "I'm begging you, stop ringing the bell!",
   "Nooo, come back, I need a cuddle!",
   "You're the reason I get up every morning!",
   "I SWEAR the vacuum won't eat you!",
   "Mommy's little angel is SO sleepy!",
   "You threw my keys behind the COUCH?!",
   "Why are you like this, you gorgeous weirdo?!",
   "Nooo, not the pie on the counter!",
   "The cucumber is harmless, I PROMISE, calm down!",
   "You've been sitting on the router ALL day!",
   "Stop running across my stomach at night!",
   "Please, I need my PILLOW back, fluffball!",
   "That was my last slice of TURKEY!",
   "You're the most dramatic kitty I've EVER met!",
   "Did you really just bite the Christmas lights?!",
   "Nooo, don't sharpen your claws on the leather!",
   "You're a warrior princess and I ADORE you!",
   "Stop kneading my stomach, it TICKLES!",
   "Why is the bread bag torn OPEN?!",
   "I SWEAR I'll feed you in two minutes!",
   "You are officially the king of this house!",
   "Pleeease stop biting the blinds at dawn!",
   "Where did you hide ALL my earrings?!",
   "How did you get stuck behind the FRIDGE?!",
   "My whole bed is COVERED in your fur!",
   "Nooo, the bathtub is full of water!",
   "Oh, you precious little chonky BABY!",
   "Stop meowing at the bird, it can't hear you!",
   "I love your stinky little tuna breath!",
   "Get down from the bookshelf before it FALLS!",
   "You unplugged my computer AGAIN, you rascal!",
   "All curled up like a little CINNAMON roll!",
   "Nooo, don't bring that lizard INSIDE!",
   "Why won't you just TAKE the pill?!",
   "Honestly, you're cuter than every puppy EVER!",
   "The groomer said you were a PERFECT angel!",
   "Pleeease stop eating the dog's FOOD!",
   "You knocked over the whole FISHBOWL?!",
   "Stop sulking, I only left for a weekend!"
  ]
 },
 "5": {
  "short": [
   "Okay, you can have one more treat, but that's it.",
   "Good morning, kitty, did you sleep well on my face?",
   "Please get off the kitchen counter, I'm cooking here.",
   "Yes, I see the box, it's a very nice box.",
   "Dinner is in ten minutes, you can wait, I promise.",
   "Who's a handsome boy? You are, mister whiskers.",
   "Why are you staring at the wall again, buddy?",
   "I know you want tuna, but this is chicken.",
   "The vet is not that scary, I promise, little one.",
   "Please stop sitting on my keyboard while I'm typing.",
   "Is that a hairball on the rug? Wonderful, thank you.",
   "That's not a gift, sweetie, that's a dead leaf.",
   "Stop knocking my pen off the desk, I see you.",
   "Fine, you can have the warm spot on the couch.",
   "Want to play with the laser pointer for a bit?",
   "The vacuum is just a machine, it won't eat you.",
   "You're sitting on my laptop again, little floof.",
   "I'm not falling for the belly again, nice try.",
   "Chin scratches? Sure, come here, you sweet little thing.",
   "Please leave the Christmas tree alone this year, okay?",
   "Be nice to the dog, he's trying his best.",
   "I cleaned the litter box this morning, you're welcome.",
   "You already had breakfast, don't pretend you didn't.",
   "Why do you drink from my glass and not yours?",
   "That's my chair, but I guess it's yours now.",
   "Look at you, all curled up like a cinnamon roll.",
   "Did you just bring me a sock? Thank you, I think.",
   "It's raining outside, you really don't want to go out.",
   "Please stop scratching the sofa, you have a scratching post.",
   "I'm on a call, can you please be quiet for once?",
   "You can't fit in that box, but go ahead and try.",
   "Sorry, that fish is for me, not for you.",
   "Your bowl isn't empty, there's just a tiny gap in the middle.",
   "Who knocked the plant over? Don't look at me like that.",
   "Nap time already? You just woke up ten minutes ago.",
   "I love you, but please stop biting my ankles.",
   "The red dot is gone, it's not under the couch.",
   "Yes, I'm home, I missed you too, kitty.",
   "You don't need to supervise me in the bathroom, you know.",
   "Come sit on my lap, I promise I won't move.",
   "That bird outside can't hear you chattering at it.",
   "You were on the counter again, weren't you? I saw fur.",
   "Please don't eat the ribbon, it's not a noodle.",
   "You look very proud of yourself, what did you break?",
   "The dog is allowed on the couch too, you know.",
   "Stop meowing at the door, you've never been outside.",
   "Is it snack time already, or are you just bored?",
   "Your tail is in my coffee, sweetheart.",
   "I bought you a new toy and you prefer the bag.",
   "You're a very good hunter, but please stop hunting my toes.",
   "Don't worry, we're only going to the vet for a checkup.",
   "You can sleep on my pillow, I'll use the corner.",
   "Why are you yelling at your reflection, silly kitty?",
   "The fridge door opening doesn't always mean food for you.",
   "Thank you for the hairball in my shoe, very thoughtful.",
   "Mister whiskers, please get down from the bookshelf, carefully.",
   "I see you eyeing my sandwich, and the answer is no.",
   "Okay, three more minutes of chin scratches, then I'm working.",
   "You're shedding on my black pants on purpose, aren't you?",
   "It's just thunder, sweetie, come hide under the blanket with me.",
   "You don't have to follow me into every single room.",
   "Yes, the sunbeam moved, you'll have to move too.",
   "I know you hate the carrier, but we have to go.",
   "Leave the ornaments on the tree, please, they're glass.",
   "Stop batting at the dog's tail, he's trying to sleep.",
   "My meeting starts in five minutes, please be a good kitty.",
   "That's the third time you've knocked that cup over today.",
   "The tuna is coming, I'm opening the can right now.",
   "Yes, the laser is back, go get it, tiger.",
   "Are you purring or plotting something? I honestly can't tell.",
   "You really do love that crinkly paper, don't you?",
   "Stop sitting in the laundry basket, those are clean clothes.",
   "You're warm and fuzzy and I adore you, little floof.",
   "Can I please have my blanket back, your highness?",
   "You don't need to sniff every grocery bag, it's lettuce.",
   "I'm sorry I stepped on your tail, I didn't see you.",
   "The zoomies can wait until morning, can't they, buddy?",
   "Your brother didn't steal your food, you already ate it.",
   "I'm brushing you now, hold still, it'll be quick.",
   "You have a whole cat tree and you choose the printer.",
   "Please don't lick the butter, we've talked about this.",
   "Look at those little toe beans, I could squish them.",
   "Your water fountain is full, I promise, go look.",
   "No, you can't come in the shower with me.",
   "You caught the toy mouse? What a brave little hunter.",
   "Please stop chewing on the phone charger, it's dangerous.",
   "Oh, now you want cuddles, right when I'm leaving.",
   "You're not allowed in the closet, you'll get stuck again.",
   "You smell like the dog, did you two nap together?",
   "Please don't push the remote off the table again.",
   "We'll try the new food tomorrow, and you'll hate it.",
   "It's a cucumber, sweetie, it's not going to hurt you.",
   "Stop pawing at my face, I'm getting up, I'm getting up.",
   "You are the fluffiest fluffball in the whole neighborhood.",
   "I know the window is fun, but dinner is ready.",
   "That is my yogurt lid, not yours, but fine, lick it.",
   "Did you knock my keys off the hook again, mister?",
   "I made you a little fort out of the delivery box.",
   "Please use the litter box and not the bathtub, sweetheart.",
   "You're so soft, how are you this soft?",
   "Why are you sitting on the paper I'm reading?",
   "That's a shoelace, not a snake, you can relax now.",
   "Okay, one belly rub, but if you bite me, we're done.",
   "Stop yelling at the birds, they're not coming inside, kitty.",
   "The cursor on the screen is not a mouse, I promise.",
   "Welcome back, did you enjoy your nap in the sink?",
   "I'll feed you at seven, same as every single day.",
   "You got catnip on the carpet again, you little rascal.",
   "Please don't sleep in the dryer, it scares me half to death.",
   "Goodnight, little floof, please let me sleep until the alarm."
  ],
  "long": [
   "Nooo, not the belly trap AGAIN, I fell for it!",
   "Pleeease get off the keyboard, I'm in a meeting!",
   "Oh my gooosh, you are the cutest kitty in the world!",
   "It is FOUR in the morning, why are you screaming?",
   "Whyyy did you knock my coffee onto the floor?",
   "Okay okay OKAY, the tuna is coming, stop yelling!",
   "Nooo, not the Christmas tree, I just decorated it!",
   "Mister whiskers, I love you sooo much, you perfect angel!",
   "Pleeease stop zooming across my face at three a.m.!",
   "The vacuum is NOT a monster, please come out, baby!",
   "I just cleaned that rug, and you threw up on it!",
   "Why is there a mouse in my slipper? Whyyy?",
   "You already ate TWICE, you are not starving, I promise!",
   "Get DOWN from the counter, that's where we make food!",
   "Nooo, not the carrier face, we HAVE to see the vet!",
   "Look at your tiny little paws, I can't handle it!",
   "Oh nooo, that was my favorite mug, sweetheart!",
   "You are the fluffiest, squishiest, most perfect floof EVER!",
   "Pleeease don't eat the tinsel, we cannot do this again!",
   "Stop chasing the dog, he is TERRIFIED of you!",
   "Fifty dollars on that bed, and you pick the box!",
   "Whyyy are you staring at me like I owe you money?",
   "Okay, FINE, you can have the whole pillow, your majesty!",
   "You are SITTING on my homework, please move, pleeease!",
   "The red dot is NOT under the couch, I swear!",
   "Nooo, don't push that glass, don't you dare, noooo!",
   "I have been scooping this litter box ALL week!",
   "You brought me a LIZARD? Inside? Why, kitty, whyyy?",
   "Oh my heart, you're purring so loud, I love you!",
   "That was my SANDWICH, you little furry thief!",
   "Stop meowing at the fridge, it will NOT open itself!",
   "You are not starving, you are DRAMATIC, my little floof!",
   "Pleeease, just one photo where you look at the camera!",
   "The hairball was on my PILLOW, kitty. My pillow!",
   "Come baaack, I only wanted to trim ONE little claw!",
   "I'm sooo sorry I sneezed, please don't leave the room!",
   "You're the best boy in the whole entire universe, yes you are!",
   "Why do you ONLY love me when I'm eating fish?",
   "My laptop is not a heated bed, get OFF it!",
   "Noooo, not the curtains, those were brand new!",
   "You ate the string again? We are going to the VET!",
   "Who's my sweet little fluffball? YOU are! Yes you are!",
   "It's three a.m., why are you playing soccer with a grape?",
   "Please stop walking across my face at DAWN, I beg you!",
   "You woke me up for THIS? A bowl that's barely half empty?",
   "Stop biting the dog's ears, he is a gentle giant!",
   "I opened the door and you just STARED at it?",
   "Oh, my little baby, did the vacuum scare you? Come here!",
   "Sooo many toys, and you want the bottle cap. Of course!",
   "You are NOT allowed inside the Christmas tree, get out!",
   "My boss saw your whole butt on camera, kitty!",
   "You clawed my brand new couch, I am heartbroken!",
   "Pleeease don't give me another dead bug, I'm begging!",
   "I love your little face sooo much, I could cry!",
   "Stop yelling, I'm opening the can as fast as I can!",
   "Why did you pee next to the litter box? WHY?",
   "Tuna is for SPECIAL occasions, and Tuesday isn't special!",
   "You knocked every single thing off my nightstand, every one!",
   "I am NOT sharing my salmon, stop looking at me like that!",
   "Come down from the fridge, you'll hurt yourself, baaaby!",
   "You swatted the dog AGAIN, he just wanted to say hi!",
   "The keyboard is not a bed, you typed four hundred Ks!",
   "You are sooo warm and cuddly, never ever leave me!",
   "Oh noooo, you're shedding all over my wedding clothes!",
   "PLEASE stop drinking out of the toilet, it's gross!",
   "Kitty, you ate a whole ribbon? Why would you DO that?",
   "I am begging you, stay OFF the counter for once!",
   "Five whole minutes of chin scratches and you STILL want more?",
   "Heyyy, that's my spot, I just got up for one second!",
   "Why do you hate the vet? She LOVES you, sweetie!",
   "The laser is gone, it's GONE, stop staring at the wall!",
   "Stop biting my toes under the blanket, it's MIDNIGHT!",
   "Oh, you want to cuddle NOW? Right when I'm late?",
   "You look like a tiny loaf of bread and I LOVE it!",
   "Do NOT throw up on the carpet, the floor is right there!",
   "My dinner is NOT your dinner, little mister whiskers!",
   "How are you THIS fluffy? It should be illegal!",
   "Stop screaming at the bird, it cannot HEAR you, sweetie!",
   "Why do you chase your own tail? It's attached, silly!",
   "Don't you DARE bite me after I rubbed your tummy!",
   "You tore open the treat bag? The WHOLE bag?",
   "Noooo, you knocked over the tree for the third time!",
   "My little fluffball, I missed you sooo much today!",
   "Pleeease stay still, I'm just brushing out the knots!",
   "You are the reason I own a lint roller, kitty!",
   "I can't work with your tail in my face, pleeease!",
   "You broke my glasses chasing the laser, oh noooo!",
   "I only left for five minutes, why are you crying?",
   "The box is EMPTY, why is it your favorite thing?",
   "You're hiding under the bed AGAIN because of the doorbell?",
   "That's the dog's food, not yours, you little thief!",
   "You scratched the vet, and now I'm SO embarrassed!",
   "I love you more than coffee, and that's saying a LOT!",
   "Stop licking the plastic bag, it's not DELICIOUS, it's plastic!",
   "You sat on the remote and ordered a MOVIE, kitty!",
   "Why is the toilet paper shredded all over the hallway?",
   "You're not a lap cat, you're a FACE cat, get down!",
   "It's six a.m. on a SATURDAY, go back to sleep!",
   "Mister whiskers, you smell like the garbage, what did you DO?",
   "That bug is bigger than you, pleeease leave it alone!",
   "You are so SPOILED and I wouldn't change a thing!",
   "Please take your paw OUT of my cereal, sweetheart!",
   "The water glass is MINE, you have a fountain, kitty!",
   "Oh, you're so sleepy, look at your little yawn!",
   "You unrolled the whole paper towel roll? All of it?",
   "Stop hissing at the dog, he's been here longer than you!",
   "I just bought you a heated bed, and you hate it?",
   "Nooo, not the zoomies during my yoga, pleeease!",
   "You're the love of my life, just don't tell the dog!",
   "You bit me AGAIN, right after I gave you belly rubs!"
  ]
 },
 "6": {
  "short": [
   "I know you're hungry, but it's four in the morning, so please go back to sleep.",
   "Okay, you can sit on my lap, but I have to get up in ten minutes, fair warning.",
   "The vet appointment is at two, so please don't hide under the bed like last time.",
   "I'm going to the store now, be good, don't knock anything over, and I'll bring back treats.",
   "You have a whole bowl of food, but you want me to stand here and watch you eat.",
   "I appreciate the mouse, really, but next time you can just keep it for yourself.",
   "You are welcome to sit on my laptop, as long as you don't send any emails.",
   "Every morning you act like I've never fed you before in your entire life.",
   "We've been over this, the counter is for people, and the floor is for kitties.",
   "I bought you three new toys and you are playing with a hair tie again.",
   "Look, the dog isn't going to hurt you, he just wants to sniff your tail.",
   "If you keep sitting in front of the TV, nobody gets to see the ending.",
   "You can have a little bit of my fish, but don't tell anyone I did this.",
   "I'm going to vacuum now, so you might want to go hide in the closet.",
   "I cleaned the litter box twice today, so I'm not sure what you're complaining about.",
   "You don't have to sleep right on top of my head, there's a whole bed here.",
   "That Christmas tree is not a climbing gym, no matter what you've heard from other cats.",
   "I know you love the laser pointer, but my arm is getting tired, buddy.",
   "You get one chin scratch every time you walk past, that's the rule, apparently.",
   "Why is it that you want to go outside only when it's raining?",
   "I'm in a meeting, so please don't walk across the keyboard and unmute me again.",
   "You've been napping for six hours, so I'm not sure what exactly you're tired from.",
   "I promise dinner comes at the same time every day, you don't need to remind me.",
   "Could you please stop bringing leaves inside and leaving them on my pillow?",
   "I love that you want to help, but folding laundry is harder with you in it.",
   "You can't catch the bird through the window, but I admire your dedication, sweetie.",
   "Hey mister whiskers, you have something on your nose, come here and let me get it.",
   "When I open the fridge, it's not always for you, but I get why you'd think that.",
   "I'm not sure why you need to watch me brush my teeth every single night.",
   "We moved your food bowl two feet, and you're acting like the world has ended.",
   "I think you had a hairball, and I think it's in my slipper, isn't it?",
   "You're allowed to sleep in the sun, but please don't block the whole doorway.",
   "If you knock that glass off the table, you're cleaning it up yourself, mister.",
   "I know you think the dog's bed is better, but he's looking at you sadly.",
   "Okay, one more round with the feather toy, and then it's time for bed, little floof.",
   "You were totally fine with the carrier until you saw it, and now look at you.",
   "It's so nice to come home to you, even if you just want dinner.",
   "Why did you choose the one spot on the couch where I was about to sit?",
   "You don't need to guard the bathroom door, I'm coming right back out, I promise.",
   "You've been staring at that corner for ten minutes, is there a ghost I should know about?",
   "I see you slowly pushing my phone toward the edge, and I'm asking you not to.",
   "When I say we're going to the vet, you somehow always disappear into another dimension.",
   "If you wanted tuna, you could have just asked nicely instead of screaming at the pantry.",
   "The printer is not a warm bed, even though I understand why you think so.",
   "Thank you for the leaf you brought me, I'll keep it on the shelf forever.",
   "You can't be hungry, I literally just fed you twenty minutes ago, remember?",
   "I love you, but I'm not waking up at five just because the birds are.",
   "You knocked the pen off my desk, so now I have to pick it up again.",
   "Please try to use the scratching post, it cost more than the couch did.",
   "I think we both know who really owns this apartment, and it isn't me.",
   "You're sitting on my book, which means you want attention, not reading time, right?",
   "You don't need to sniff my shoes every time I come home, I was just at work.",
   "The Christmas lights are pretty, I know, but they are not for chewing on, kitty.",
   "I'm heading to bed now, so please save the zoomies for tomorrow afternoon.",
   "Do you want to come sit in the sunshine with me, or are you busy judging me?",
   "I'll trade you one treat for letting me trim a single claw, deal?",
   "You've got your cute face on, which means you probably just broke something.",
   "That's a very nice gift, sweetie, but honestly, I would have preferred a sock.",
   "I'm putting the dishes away, so please stop batting at every spoon I hold.",
   "We don't hiss at the dog, we say hello politely and walk away.",
   "If you're going to sit on the keyboard, at least type something useful for me.",
   "You're a bit round lately, so we're going easy on the treats this week, buddy.",
   "I found your toy mouse under the fridge, along with three hair ties and a grape.",
   "Okay, the box can stay in the living room, since you clearly live there now.",
   "You don't have to announce every single time you use the litter box, kitty.",
   "I'm not sure why you drink from the faucet when your fountain is right there.",
   "You can have the warm laundry for five minutes, then it has to be folded.",
   "It's not a belly rub invitation, is it? It's a trap, and I know it.",
   "You're purring so loud I can barely hear my show, and honestly, I don't mind.",
   "I'm sorry the vacuum exists, but the floor needs it, and so do my allergies.",
   "You don't need to supervise me cooking, I promise I'll save you a bite of chicken.",
   "You've been sitting on that paper bag for an hour, are you hatching it?",
   "Please stop yelling at me from the other room, you can just come over here.",
   "We're going to try the new food, and you're going to pretend it's poison, right?",
   "The window is closed, sweetie, so the bird can't hear your very serious threats.",
   "You're too big to fit in that tiny box, but I respect your commitment.",
   "The dog would like his bed back, if you're done sleeping in it, your highness.",
   "It's okay, the thunder can't get you, you can stay under the blanket with me.",
   "You always want to be on the other side of whatever door is closed.",
   "I brushed you yesterday and there's already enough fur here to make another cat.",
   "You're allowed on the bed, but you're not allowed to steal my entire pillow.",
   "Every time I put my shoes on, you give me that sad little face.",
   "You know, most cats sleep at night, but you seem to have your own schedule.",
   "I think it's cute when you chatter at the birds, but the neighbors can hear you.",
   "You got stuck in the closet again, so maybe we stay out of the closet?",
   "I'm working from home, which does not mean I'm home to scratch your chin all day.",
   "It's just the doorbell, sweetie, nobody is coming to take you to the vet.",
   "You can watch the fish tank, but please keep your paws out of it this time.",
   "I need you to understand that the red dot is not something you can catch.",
   "I'll be back in a few days, and the sitter will give you extra treats, I promise.",
   "You leave a trail of fur everywhere you go, like a fluffy little breadcrumb trail.",
   "Please stop sleeping in the bathroom sink, I need to wash my face in there.",
   "Whenever I sit down to eat, you suddenly become the most loving cat in the world.",
   "Mister whiskers, we talked about this, the curtains are not a ladder.",
   "I found another hairball behind the couch, so thank you for that little surprise.",
   "You can sit next to me on the couch, but the remote belongs to me, kitty.",
   "I'm on the phone with grandma, so please stop meowing, she thinks I'm a cat now.",
   "You've been sleeping on my sweater all day, so I guess it's your sweater now.",
   "Your breakfast is at seven, not six, not five, and definitely not three.",
   "You follow me everywhere I go, but the second I pick you up, you run away.",
   "The ornaments look much better on the tree than under the couch, sweetie.",
   "Okay, fine, I'll scratch behind your ears, but only because you're very cute.",
   "I'm not sure the goldfish appreciates you staring at him all afternoon, buddy.",
   "We have a scratching post, a cat tree, and three beds, yet here you are on my chair.",
   "It's great that you love the box so much, but I need to recycle it eventually.",
   "You look so peaceful when you sleep, it's hard to believe you're a tiny menace.",
   "Let's go easy on the catnip, you were bouncing off the walls last time.",
   "You woke me up to show me you were awake, which was very thoughtful of you.",
   "Goodnight, little floof, I'll see you at three a.m. when you decide to play.",
   "You can come help me garden, but please don't dig up the tomatoes this time."
  ],
  "long": [
   "I have been on this video call for FIVE minutes and you've shown everyone your whole butt twice!",
   "Pleeease, I am begging you, stop screaming at the door at four in the morning, the sun isn't even up!",
   "Oh my gooosh, look at your little whiskers and your little nose, I cannot take how cute you are!",
   "You bit me AGAIN, I gave you a belly rub like you asked, and this is the thanks I get?",
   "I spent SO much money on that fancy bed and you're sleeping in the cardboard box it came in!",
   "Nooo, not the Christmas tree, I spent three hours on those ornaments, please get down right now!",
   "The vacuum is NOT going to eat you, sweetie, please come out from under the bed, pleeease!",
   "You already had breakfast, second breakfast, and a snack, you are NOT starving, you little drama queen!",
   "Why do you wait until I'm fast asleep to start doing zoomies across my entire body at three a.m.?",
   "I said NO more tuna, but you're doing the eyes, and oh no, it's working, fine, one bite!",
   "Mister whiskers, you are the most handsome, fluffy, perfect boy in the whole wide world, yes you ARE!",
   "Get DOWN from the counter, I am making dinner, and your tail is literally in the pasta sauce!",
   "You brought a live mouse into the house, and now it's under the fridge, thank you SO much!",
   "Pleeease, just let me put you in the carrier, the vet is nice, she gives you treats, remember?",
   "Why is there a hairball in my shoe, why THIS shoe, why always the left one, whyyy?",
   "I was going to give you a treat, but you knocked my coffee on the floor, so now I'm thinking!",
   "The dog is TERRIFIED of you, can you please let him walk past without swatting his nose?",
   "I have never loved anything as much as I love your squishy little face, you perfect floof!",
   "Every single night you drop a toy in my shoes, and every single morning I step on it!",
   "You are sitting on my laptop during my presentation, and my boss just said hello to you!",
   "It's three in the morning, why are you knocking every single thing off my dresser one by one?",
   "Nooo, don't eat the tinsel, we did that last year, and it was NOT a fun trip to the vet!",
   "I opened the door you screamed at for ten minutes and now you don't want to go through it?",
   "My sweet little fluffball, I missed you sooo much, did you miss me, or just my can opener?",
   "You shredded the toilet paper AGAIN, the whole roll, it looks like it snowed in the bathroom!",
   "Okay, okay, OKAY, I hear you, dinner is coming, please stop biting my ankles while I open the can!",
   "The laser is OFF, kitty, it's gone, there's nothing on the wall, please stop staring at it!",
   "Why do you ignore the brand new toy I bought and fall in love with the receipt instead?",
   "You threw up on the carpet, right next to the tile floor, which would have been SO easy to clean!",
   "I cannot believe you climbed the curtains AGAIN, they are hanging by one hook now, sweetie!",
   "Pleeease stop drinking from my water glass, you have your own fountain that cost me forty dollars!",
   "I just want ONE photo where you're looking at the camera and not your own butt, pleeease!",
   "You scratched the brand new couch, the one I saved for, and you look so proud of yourself!",
   "I have scooped that litter box every day this week and you STILL go right next to it!",
   "My sweet angel, you are purring so loud the neighbors can probably hear you, I love it SO much!",
   "Stop pawing at my face every morning, I KNOW you're hungry, I'm getting up, I'm getting up!",
   "Every time you show me your tummy I think this time will be different, and it NEVER is!",
   "Please stop chasing the dog around the house, he's twice your size and he's scared of you!",
   "I bought the fancy salmon pate and you took one sniff and walked away like I insulted you!",
   "Whyyy are you meowing at the empty wall like there's a ghost, you are scaring me, kitty!",
   "You woke me up at five to show me a leaf, a single LEAF, that you found in the hallway!",
   "I just vacuumed the whole house and you immediately rolled in a pile of dust, how, just how?",
   "You sat on the keyboard and deleted my ENTIRE essay, and now you're taking a nap on it!",
   "I leave for ONE weekend and you act like I abandoned you for a whole year, you drama queen!",
   "The Christmas tree is on the floor, the ornaments are everywhere, and you're sleeping in the box!",
   "Oh noooo, the baby is scared of the doorbell, come here, it's just the pizza, you're safe!",
   "How are you so fluffy and so soft and so warm, it should honestly be against the law!",
   "Stop sitting on my book, please, I just want to read ONE chapter without your tail in my face!",
   "You ate a hair tie AGAIN, do you know how much the vet charges for that, sweetheart?",
   "I am begging you, please don't knock the plant over, I JUST repotted it this morning!",
   "Get out of the dryer RIGHT now, you scared me half to death, that is NOT a bed!",
   "You ignored me all day and now that I'm finally asleep, you want to snuggle, seriously?",
   "You chewed through my phone charger, my headphones, AND my good shoelaces, what is going on with you?",
   "I love you more than pizza, more than sleeping in, and more than my own couch, which you ruined!",
   "That bird is outside, the window is closed, and yelling at it has not worked ONCE, kitty!",
   "Why do you only want belly rubs when I'm running late, and then bite me when I stop?",
   "Pleeease stop dunking your paw in my cereal, I'm trying to eat breakfast like a normal person!",
   "You unrolled the entire paper towel roll across the kitchen, and now you're wrapped in it like a burrito!",
   "Every time I sit down you jump on my lap, every time I stand up you look SO betrayed!",
   "My little floof, you're the best thing that ever happened to this apartment, fur and all!",
   "You slapped the dog AGAIN, and he just wanted to share his bed with you, you grumpy baby!",
   "I am on a VERY important call, please stop meowing into the microphone like you're the boss!",
   "Your hairball landed on my freshly washed sheets, the ones I literally just put on the bed!",
   "Stop hiding my socks under the couch, I have found eleven so far, and I need them for WORK!",
   "You yell at me for food, I give you food, and then you walk away, what do you WANT?",
   "I trimmed ONE claw and you screamed like I was ruining your entire life, you big baby!",
   "The cursor is NOT a bug, stop swatting at my screen while I'm trying to finish my work!",
   "You are the sweetest, softest, squishiest little bean in the entire universe and I will never let you go!",
   "Why did you bring me a dead moth at midnight, and why did you put it on my pillow?",
   "I made you a whole cardboard castle with windows and towers, and you're sleeping in the recycling bin!",
   "Nooo, you knocked the fishbowl over, the goldfish is fine, but you are in SO much trouble!",
   "You licked the butter again, the whole stick has tiny tongue marks in it, what am I supposed to do?",
   "Please stop running on the stairs at night, you sound like a herd of elephants, little one!",
   "You are NOT allowed to sleep on the stove, I don't care how warm it was, get down!",
   "I gave you chin scratches for twenty minutes and the second I stopped you stared at me like a villain!",
   "Pleeease don't hide in the closet again, I searched the whole house for you for an hour!",
   "You fell off the couch and then looked at me like it was MY fault, how is that my fault?",
   "It's six a.m. on a SUNDAY, the one day I sleep in, and you're sitting on my chest!",
   "You shed on EVERY piece of black clothing I own, it's like you do it on purpose, don't you?",
   "Why does the dog get along with you perfectly and you still hiss at him every single morning?",
   "I just washed that blanket, and you're already kneading it and drooling on it, you silly baby!",
   "Ohhh, look who wants cuddles now that it's cold outside, you only love me for my body heat!",
   "You stole a whole shrimp off my plate and ran under the bed with it, you absolute little pirate!",
   "Please, PLEASE, stop biting the Christmas lights, they're plugged in and I don't want you hurt!",
   "You meowed at me until I got up, and then you went to sleep on MY warm spot!",
   "You spent all night hunting a single cereal piece across the kitchen and honestly I'm very proud of you!",
   "I have told you a HUNDRED times, the bathtub is not a litter box, sweetheart!",
   "Look at those toe beans, look at that fluffy tummy, I know it's a trap, but I love it!",
   "You finally caught the red dot, and it was on my forehead, and now I have a scratch!",
   "Stop yelling at the vacuum, it's turned OFF, it's just sitting there, it's not going to move!",
   "You broke into the treat cabinet, ate half the bag, and now you're napping like nothing happened!",
   "Oh my goodness, you fell asleep with your tongue out, I'm taking a hundred pictures of this!",
   "Mister whiskers, why is there a sock in your food bowl, and why is it MY sock?",
   "I swear you know exactly when I'm about to take a sip of coffee, and that's when you jump!",
   "I put the fish on the table for ONE second and now it's gone, and you have a guilty face!",
   "The whole meeting just watched you knock my water bottle off the desk, and they all LOVED it!",
   "Please come back inside, it's pouring rain, and you've been staring at the puddle for ten minutes!",
   "You ran across my keyboard, sent my boss a message that said zzzzzzz, and now I have to explain!",
   "You've been yelling at your own reflection in the oven door for twenty minutes, it's just you, baby!",
   "I let you sleep under the covers once, ONCE, and now you think you own the entire bed!",
   "You are too heavy to sit on my chest, sweetie, I can't breathe, but I also can't move you!",
   "I came home from the vet with you, and you're giving me the silent treatment for the whole week!",
   "Why do you insist on sleeping on the exact piece of paper I need to sign right now?",
   "You chased your tail for five minutes, caught it, bit it, and then got mad at me about it!",
   "I love you, I adore you, you are my whole world, but please stop licking my hair at night!",
   "You are NOT a dog, stop trying to eat the dog's food, you have your own bowl right there!",
   "I heard the crash from the other room, and I'm scared to look, what did you knock over NOW?",
   "You climbed into the grocery bag, got stuck, and ran through the whole house wearing it like a cape!",
   "Pleeease stop bringing me gifts from the garden, I don't need another worm on my doormat!",
   "You're sitting on my chest and staring into my soul at dawn, and honestly, I kind of love it!"
  ]
 }
};
