// Cat-to-English phrase book: CAT_PHRASES[meowCount]["short" | "long"].
// "short" = normal meows, "long" = drawn-out meows. 6 means 6 or more.
window.CAT_PHRASES = {
 "3": {
  "short": [
   "I like mice.",
   "That's my chair.",
   "I saw a bird.",
   "The bowl looks empty.",
   "Your keys are gone.",
   "I knocked it over.",
   "The box is mine.",
   "Pet me. No, stop.",
   "The vacuum must go.",
   "Open this door now.",
   "I heard a can.",
   "The dog smells weird.",
   "Your lap, please.",
   "I ate your plant.",
   "That was on purpose.",
   "I live here now.",
   "Nap time again.",
   "Where is breakfast?",
   "The red dot escaped.",
   "I found a hairball.",
   "It's in your shoe.",
   "Your sweater is fur now.",
   "I am a predator.",
   "Fear my tiny teeth.",
   "Catnip changed my life.",
   "The vet lied.",
   "I bit you lovingly.",
   "Move over, human.",
   "The sunbeam moved.",
   "I own this couch.",
   "That bag is mine.",
   "Fetch? How undignified.",
   "Mondays are for napping.",
   "Your keyboard is warm.",
   "Tuna, please. Now.",
   "The fish stares back.",
   "I judge your outfit.",
   "Stop singing, please.",
   "That's not my name.",
   "Water must be moving.",
   "I prefer the faucet.",
   "The toilet paper lost.",
   "I wasn't on the counter.",
   "Who moved my blanket?",
   "I brought you a sock.",
   "That's a gift. Rejoice.",
   "Nice try, bath.",
   "I refuse the harness.",
   "The carrier means betrayal.",
   "Squirrel. Outside. Now.",
   "Birds are mocking me.",
   "The mailman returns.",
   "I guard the window.",
   "The ceiling ghost again.",
   "I stared at nothing.",
   "Something is in the wall.",
   "Litter box. Check it.",
   "I scratched the good couch.",
   "The scratching post bores me.",
   "The mug fell. Oops.",
   "Gravity still works.",
   "I sit on papers.",
   "Your homework is my bed.",
   "I'm too cute to scold.",
   "Blink slowly back.",
   "Belly rub? It's a trap.",
   "My tail did that.",
   "I won the tail fight.",
   "Kibble is beneath me.",
   "The good cans, please.",
   "Is that chicken?",
   "Share your sandwich.",
   "I smell cheese.",
   "Butter is my friend.",
   "That yarn looked suspicious.",
   "The string is alive.",
   "I caught a bug.",
   "Crunchy bug, delicious.",
   "The dog stole my spot.",
   "Cucumbers are terrifying.",
   "The bag crinkled.",
   "The curtains are climbable.",
   "Your phone fell. Weird.",
   "I'm the boss here.",
   "Ignore me? Your loss.",
   "I changed my mind.",
   "Outside looks boring now.",
   "My whiskers sense danger.",
   "The laser is back.",
   "I'm too sleepy today.",
   "Eighteen hours isn't enough.",
   "Wake me for tuna.",
   "Your pillow is mine.",
   "I sleep diagonally now.",
   "The printer is warm.",
   "I sent your email.",
   "I hate the doorbell.",
   "Guests? I'm hiding.",
   "The ribbon was delicious.",
   "I'm plotting something.",
   "Don't look at me.",
   "Treats solve everything.",
   "This sink fits me.",
   "I lost my mouse.",
   "Your plant looked chewy.",
   "The moth is mine.",
   "Brushing is acceptable. Continue.",
   "I bathe in public.",
   "The fridge opened. Hello.",
   "Bedtime? I'm wide awake."
  ],
  "long": [
   "Whyyyy is it empty?",
   "I'm STARVING. Truly.",
   "Feed me or perish.",
   "The bowl has a HOLE.",
   "Nooo, not the vet!",
   "The vacuum is BACK.",
   "Save meeee from it.",
   "Open the doooor!",
   "Let me ouuut!",
   "Let me back iiiin!",
   "I have NEVER eaten.",
   "My dinner is LATE.",
   "Two minutes late. Unforgivable.",
   "The bird got awaaay.",
   "I'm wasting awaaay.",
   "Look at my ribs!",
   "Nobody loves meeee.",
   "Pet me foreverrrr.",
   "Why did you leave?!",
   "You were gone FOREVER.",
   "Five minutes felt like years.",
   "The dot is GONE.",
   "Where did it gooo?",
   "Tuuuuna. I need tuna.",
   "Chicken! I smell chickennn!",
   "It's 3am! ZOOMIES!",
   "I must run NOW.",
   "The hallway calls meeee.",
   "I saw a GHOST.",
   "Something moved over thereee.",
   "The cucumber attacked meee!",
   "Betrayed by the carrier!",
   "Not the bath. PLEASE.",
   "I'm soaking wet. Tragic.",
   "My dignity is ruined.",
   "The dog is BREATHING.",
   "Make the dog leave.",
   "The box is too smalll.",
   "I still fit. Mostly.",
   "Who closed this dooor?",
   "I'm on the wrong side!",
   "The sun went awaaay.",
   "My blanket was WASHED.",
   "It smells like soap. Gross.",
   "Hairball incoming! Brace yourself!",
   "Hhhhack. Hhhhack. Sorry.",
   "I'm stuck up hereee!",
   "The tree betrayed me.",
   "Nobody warned me about gravity.",
   "You moved the furniture?!",
   "Everything is differrrent now.",
   "Where is my mouse?!",
   "You threw it OUT?!",
   "The laser, I beg you.",
   "Just one more treeeat.",
   "I deserve ALL the treats.",
   "I'm so misunderstood.",
   "I'm a majestic predator!",
   "Fear meeee, tiny bug!",
   "The fly mocks meee.",
   "The birds are laughing!",
   "The squirrel is TAUNTING me.",
   "Let me at itttt!",
   "Catnip, my sweet catnip.",
   "The catnip is GONE?!",
   "The doorbell! Hide everything!",
   "Strangers! In MY house!",
   "I'm under the bed. Forever.",
   "My tail! It's following me!",
   "Brush me. No, STOP.",
   "Don't touch the belly!",
   "You woke me UP.",
   "I was dreaming of fish.",
   "Ughhh, it's raining again.",
   "Wet paws. The horror.",
   "My water is STALE.",
   "It's been sitting an HOUR.",
   "The faucet, turn it onnn.",
   "This food is YESTERDAY'S.",
   "Who bought this flavor?!",
   "Love meee! Now leave.",
   "Why are you packing?!",
   "The suitcase means abandonment!",
   "Don't goooo to work!",
   "Your laptop gets more attention!",
   "Look at ME instead.",
   "The glass had it coming!",
   "Whisker fatigue is real!",
   "You sneezed. How DARE you.",
   "Your music hurts my ears!",
   "The printer is screaming!",
   "The blender! RUN!",
   "Thunder! The sky is ANGRY!",
   "I'm too pretty for this.",
   "Bow before your ruler!",
   "Nine lives isn't enough!",
   "My life is so haaard.",
   "Life is sufferinggg. Pet me.",
   "Shut the fridge? NOOO!",
   "The pill! Not the pill!",
   "My nails! Put those down!",
   "You pet the DOG?!",
   "I've been ignored for SECONDS.",
   "The heater is OFF!",
   "My toy is under the couuuch!",
   "A leaf touched me! Help!",
   "Your lap is LEAVING?!",
   "I'm freezing in this sunbeam.",
   "Stop the hairdryer! Monster!",
   "Where are my treeeats?"
  ]
 },
 "4": {
  "short": [
   "The red dot got away again.",
   "Your laptop is my bed now.",
   "I knocked your pen off the desk.",
   "The bird outside the window mocks me.",
   "I would like second breakfast, please.",
   "Your chair is warmer than my bed.",
   "The dog is not welcome in here.",
   "I sat in the box you ordered.",
   "I hid a hairball in your slipper.",
   "The vacuum and I are enemies forever.",
   "I'm going to the vet? Absolutely not.",
   "Please stop moving the blanket I'm on.",
   "Zoomies start at 3am. Be ready.",
   "I sprinted through the hall for no reason.",
   "That glass was too close to the edge.",
   "I am a fierce and majestic predator.",
   "I caught a moth and lost it.",
   "The closed door offends me deeply.",
   "I just want to see the closet.",
   "Catnip made me see the universe.",
   "The bathroom door must stay open always.",
   "I'll watch you shower, thank you.",
   "You touched the belly. Now you pay.",
   "I accept your offering of chicken.",
   "Your sandwich looks lonely. I can help.",
   "The fridge opened. I heard it upstairs.",
   "The can opener is my favorite song.",
   "I scratched the couch, not the post.",
   "The box matters more than the gift.",
   "Nobody asked, but I'm sitting here.",
   "I typed a message to your boss.",
   "Your plant needed some trimming. You're welcome.",
   "The curtains are now my climbing wall.",
   "The laser pointer lives in your hand.",
   "Your socks are my prey now.",
   "The squirrel outside needs to be stopped.",
   "Water tastes better from your glass.",
   "Fresh water? I'll drink from the toilet.",
   "The fish tank is my TV.",
   "I ignored you. That was intentional.",
   "I came when called. Pure coincidence.",
   "I only love you at dinnertime.",
   "The mailman must be defeated today.",
   "Your yoga mat is my mat now.",
   "Downward dog? I prefer upward cat.",
   "I stared at the wall for hours.",
   "The ghost in the corner says hi.",
   "I shed on your black pants specially.",
   "I'll sleep on the clean laundry.",
   "That paper bag is my castle.",
   "The tape on the box tastes nice.",
   "Wake up. It's 5am. Feed me.",
   "I'll sit on your face until you rise.",
   "The sun spot moved without permission.",
   "I nap eighteen hours. It's exhausting.",
   "Bottle caps belong under the fridge.",
   "My toys all live under the couch.",
   "Your hair tie is my new toy.",
   "The dog tried to sniff me. Rude.",
   "The dog is a large, silly cat.",
   "That bird feeder is basically a menu.",
   "I bring you dead leaves as gifts.",
   "You're a terrible hunter. I pity you.",
   "I'll teach you to catch mice.",
   "The cucumber appeared behind me. Not okay.",
   "I'm judging you from the bookshelf.",
   "The top of the fridge is mine.",
   "The Christmas tree is my playground.",
   "Tinsel looks delicious. I must investigate.",
   "My tail has betrayed me again today.",
   "I lick myself while you have guests.",
   "The carrier is a trap. I know.",
   "I coughed up something special for you.",
   "I pushed your phone behind the dresser.",
   "Please refill my bowl to the top.",
   "The middle of the bowl is empty. Starving.",
   "I have not eaten in minutes.",
   "Pet me three times, then stop.",
   "You pet me wrong. Try again.",
   "I'll sleep between your ankles tonight.",
   "Your bed is mostly my bed.",
   "Move your legs. I claimed that spot.",
   "The radiator and I are best friends.",
   "The window is open. Adventure awaits.",
   "I saw outside once. Too big.",
   "The balcony pigeon owes me money.",
   "I'll hunt the shoelaces at dawn.",
   "The ribbon on the gift is mine.",
   "Your cardboard pile is a cat condo.",
   "I'll lie in the sink, thank you.",
   "Bath time? I'll be in another country.",
   "I refuse to wear that little sweater.",
   "No more costumes. I have dignity.",
   "Your guests should pet me, then leave.",
   "I sit on the person who hates cats.",
   "The new couch smells like my scratcher.",
   "I'll sleep in the suitcase. Stay home.",
   "Welcome home. Now serve my dinner.",
   "I smell another cat on you. Explain.",
   "My whiskers are longer than yours.",
   "I prefer the expensive food, obviously.",
   "That dry kibble is for the dog.",
   "I heard a crinkle. Was it treats?",
   "I'll pretend to be asleep for now.",
   "I licked the butter. Don't ask.",
   "The shower curtain looked at me funny.",
   "My brush feels nice. Ten more strokes.",
   "I stepped on the TV remote. Oops.",
   "Your book is closed now. I sat.",
   "I claimed the warm spot on the dryer."
  ],
  "long": [
   "Whyyyy is my bowl empty again?",
   "I have NEVER been fed. Ever.",
   "The red dot escaped and I'm devastated.",
   "You left me alone for FIVE hours!",
   "The vacuum is coming. Save meeeee!",
   "Nooooo, not the carrier, anything but that!",
   "The vet touched my tail. How DARE!",
   "Open the door! No, close it. Waaait!",
   "I've been starving since breakfast. Truly tragic.",
   "Nobody in this house appreciates meeee.",
   "My tail is chasing me. Heeeelp!",
   "The bird is RIGHT THERE. Let me out!",
   "It's 3am and I must run NOW.",
   "I'm stuck on the bookshelf foreverrrr.",
   "The sunbeam left me. I'm so cold.",
   "The box is gone? My HOME is gone?",
   "You washed my blanket. It smells WRONG.",
   "That dog is looking at me againnn.",
   "Make the dog stop existing, pleeease.",
   "I can see the bottom of the bowl!",
   "Only one treat? That's CRUEL and unusual.",
   "My catnip mouse is under the couch!",
   "Something touched my paw in the dark!",
   "The bath was the worst day ever.",
   "I am soggy and humiliated foreverrr.",
   "The doorbell rang! Everybody panic NOW!",
   "Guests? In MY house? Unacceptable!",
   "I'll be under the bed until spring.",
   "The thunder is angry at me personally!",
   "Wake up! Wake uuup! The bowl!",
   "Why are you still sleeeeping? Feed me!",
   "You pet the dog FIRST. I saw.",
   "I'm the favorite, right? RIGHT?!",
   "You looked at another cat online. Betrayal.",
   "The squirrel waved at me. I'm furious!",
   "The birds are laughing at me againnn.",
   "I'm a MIGHTY hunter trapped indoors!",
   "Let me hunt! I was born for this!",
   "The hairball is coming. Stand baaack!",
   "It landed on your pillow. Sorry, not sorry.",
   "The water is warm. It's been HOURS.",
   "I only drink from the faucet. Turn it on!",
   "This kibble has lost its crunch. Tragic!",
   "You bought the WRONG flavor again!",
   "I will simply starve out of protest.",
   "Your suitcase is out. Don't you DARE.",
   "Take me with you! I'll fit!",
   "Why do you go to work every day?!",
   "Your laptop is stealing my love!",
   "Look at me! Look at me! LOOK!",
   "I knocked it off. You weren't watching!",
   "Every door in this house is closed. Whyyy?",
   "The closet is closed. My life is over.",
   "Let me in the bathroom! What's happening?!",
   "One more round with the laser, pleeease!",
   "The toy on a string is MINE!",
   "You put the toys away? Whyyyy?",
   "Brush me until I say STOP!",
   "You touched my belly. I trusted you!",
   "I'm too beautiful to be ignored like this.",
   "I am royalty and I demand a cushion!",
   "I nearly died falling off the couch!",
   "The Christmas tree was calling me, I swear!",
   "Open the window! I need to chatter!",
   "The vacuum's cousin, the hairdryer, is HERE!",
   "You moved my food bowl two inches. WHY?!",
   "The litter box is not clean enough!",
   "I refuse that box until it's perfect.",
   "You gave my spot to the dog?!",
   "The new cat must leave immediately!",
   "I heard the can opener! Is it MINE?!",
   "The fridge opened. I came running. Share!",
   "Cheese! I smell cheese! Gimme gimme!",
   "Drop the chicken! Nobody has to get hurt!",
   "I've been awake for an HOUR. Exhausting.",
   "I need a nap after my nap.",
   "You moved while I was on your lap!",
   "Don't you dare get up. I'm comfy!",
   "The zoomies have me. I can't stop!",
   "I ran into the wall. Totally meant it.",
   "The moth outsmarted me. I'm DEVASTATED.",
   "The fly is on the ceiling. Unfair!",
   "Why can't I climb the wall?!",
   "The curtain rod is TOO high today.",
   "I jumped up here. Now I'm scared!",
   "The collar bell is ruining my stealth!",
   "You put a sweater on me. Humiliation!",
   "The photo! Delete it! My dignity!",
   "The outside cat is on MY porch!",
   "The neighbor's dog is barking at meeee!",
   "It's raining and I blame YOU personally.",
   "The heater is off. I'm freezing to death!",
   "The pillow is taken? By YOU?!",
   "I'm so lonely. You were in the shower!",
   "I was ignored for twenty whole seconds!",
   "Someone sat in my chair. Tragic!",
   "The catnip is finished. Life is meaningless.",
   "Just one sniff of catnip, pleeease!",
   "My nails are perfect. Put the clippers down!",
   "You hid the pill in my treat. BETRAYAL!",
   "I sang all night and you slept?!",
   "I brought you a leaf. Where's my applause?",
   "I caught a sock for you! Praise me!",
   "My ear itches and nobody cares!",
   "Whyyy does the dog get walks?!",
   "I've been waiting by the door ALL day!",
   "The bag crinkled but there were no treats!",
   "Pet me! No, not like that! Again!",
   "My reflection is staring at me. Rude!",
   "The mail slot attacked me AGAIN!"
  ]
 },
 "5": {
  "short": [
   "The red dot escaped again. I blame you personally.",
   "I knocked it off the table. You're welcome.",
   "That box is mine now. Deal with it, human.",
   "Your lap is warm. I will now leave it.",
   "The vacuum is my sworn enemy. Please hide me.",
   "I saw a bird. I made a weird noise.",
   "My bowl is visible at the bottom. Emergency.",
   "I sat on your keyboard. Your email is sent.",
   "The door was closed. Now open it. Now close it.",
   "I am not fat. I am fluffy and important.",
   "Your shoelaces looked at me funny. I handled it.",
   "I licked the butter. Nobody saw anything.",
   "The dog is in my spot again. Fix this.",
   "I am a majestic predator. Also, feed me.",
   "That hairball was a gift. Please treasure it.",
   "I will sleep in the laundry basket. Clean laundry only.",
   "Your plant looked lonely. I bit it for company.",
   "I'm not ignoring you. I'm just better than you.",
   "The sunbeam moved. Please move it back.",
   "Why is the vet carrier out? I'm busy forever.",
   "Catnip is not a crime. Let me live.",
   "I heard a can open three rooms away.",
   "Your phone is warm. I am lying on it.",
   "I don't do mornings. Except 5am. For breakfast.",
   "The water in my bowl is old. Ten minutes old.",
   "I prefer the faucet water. Turn it on, servant.",
   "I found a spot in the closet. Goodbye forever.",
   "That ribbon insulted my family. It had to go.",
   "Stop typing. Start petting. It's a simple system.",
   "I bring you this single sock as tribute.",
   "I have scheduled zoomies for 3am. Don't be late.",
   "The new couch is now my scratching post. Thanks.",
   "I only drink water from your glass. Obviously.",
   "Your hair tie is mine. Under the fridge. Forever.",
   "The box the gift came in is better than the gift.",
   "I'm sitting in the doorway. Choose carefully, human.",
   "Pet me exactly three times. Four means war.",
   "I was a lion in a past life.",
   "The fish tank is my television. Don't change the channel.",
   "I have decided that you are my furniture.",
   "The mailman returned. I defended us bravely again.",
   "I'll be on top of the fridge, judging.",
   "This blanket is warm. You may no longer use it.",
   "I just remembered the thing under the couch.",
   "Your homework looks comfortable. I'm sitting on it.",
   "The squirrel outside is mocking me. Open the window.",
   "I don't come when called. I come when fed.",
   "You moved. My nap is ruined. Explain yourself.",
   "I have claimed this sweater through an ancient ritual.",
   "Shhh. I'm hunting a very dangerous dust bunny.",
   "Your bed is my bed. You rent the edges.",
   "I am staring at the wall. Something is there.",
   "Tuna tonight, or I start knocking over cups.",
   "That cucumber was a declaration of war.",
   "My tail is chasing me again. Please help.",
   "I want to go outside. Now inside. Now outside.",
   "I've licked my paw. Now I'm licking your face.",
   "That's not your chair anymore. Read the fur.",
   "I'm not stuck in the tree. I'm supervising.",
   "My whiskers touched the bowl edge. Unacceptable dining conditions.",
   "The printer is alive. I must stop it now.",
   "I sat in the sink. It fits. I'm staying.",
   "Please stop sneezing. It startles my inner lion.",
   "I have hidden your earring. Good luck finding it.",
   "The dog drinks from the toilet. I am embarrassed.",
   "Brushing is fine. Stop brushing. Continue brushing.",
   "I slept for sixteen hours. I am exhausted.",
   "Your grocery bag has been inspected and approved.",
   "I want treats. I want them in a line.",
   "The ceiling fan is a big spinning bird.",
   "I've seen the laser. I know it's you.",
   "You were gone five minutes. I aged ten years.",
   "This is my serious face. Take me seriously.",
   "I kneaded your stomach. It's bread now.",
   "Please don't sing. My ears are delicate instruments.",
   "I will now walk across your face. Goodnight.",
   "The Christmas tree is a climbing gym, correct?",
   "I chirped at a bird. It was deeply personal.",
   "My brain says sleep. My legs say sprint.",
   "I stole your spot while you got water. Tough.",
   "Your cereal smells like mine. We should share.",
   "I am loafing. Do not disturb the loaf.",
   "Who moved my food bowl two inches left?",
   "My purr is a gift, not a guarantee.",
   "That was a slow blink. It means I tolerate you.",
   "The bath is a lie. I refuse to participate.",
   "I'm guarding the shower. Nothing gets past me.",
   "Your socks are warm and smell like victory.",
   "I have ruled this house for years. Quietly.",
   "Please close the curtains. The moon is watching.",
   "The paper bag is my castle. Knock first.",
   "I'm the boss. The dog just doesn't know yet.",
   "My fur belongs on your black pants. Always.",
   "I am small but my demands are large.",
   "Your video call needed a tail. I provided one.",
   "The feather wand wiggled. I lost all control.",
   "I'm stretched across the whole bed. You adapt.",
   "Look at my belly. Do not touch my belly.",
   "I pushed your pen off. It was plotting.",
   "The fridge opened. I assume that's for me.",
   "That noise was nothing. I'll stare at it anyway.",
   "My toy mouse is under the couch. Retrieve it.",
   "One day I will rule the world. Snack first.",
   "I heard the treat bag. I have arrived.",
   "Your book was in my sunbeam. I relocated it.",
   "I can't reach the bird. Buy me wings.",
   "The rug was straight. I fixed that for you.",
   "I bit you gently. It was love. Mostly.",
   "Your pillow is now my pillow. Legal and binding.",
   "That window is my office. Please respect my work."
  ],
  "long": [
   "I have been STARVING since breakfast. Eleven minutes ago.",
   "The door is CLOSED. Why would you do this to me?",
   "Nooo, not the vet! I'm too young and fluffy!",
   "The vacuum is BACK and I am not okay.",
   "My bowl is half empty. This is a TRAGEDY.",
   "Why is the red dot gone? WHERE did it go?",
   "You left for work. I thought you were gone FOREVER.",
   "Pleeease open the window. The bird is RIGHT THERE.",
   "I am so hungry I can see through time.",
   "Nobody has petted me in HOURS. Maybe minutes.",
   "The dog touched my tail. I will never recover.",
   "Whyyy is the box in the recycling? It was HOME.",
   "I fell off the couch and I demand an apology.",
   "The sunbeam is GONE. Summon it back immediately.",
   "Let me OUT. No wait, let me back IN.",
   "My food touched the side of the bowl. Ruined. RUINED.",
   "This hairball is my masterpiece. Why are you screaming?",
   "You brought home ANOTHER cat's smell. How could you?",
   "Oh, the betrayal. You gave the dog a treat first.",
   "The bath water touched my paw. I am drowning!",
   "I am the most neglected cat in human history.",
   "Your laptop is getting ALL the attention. Choose me!",
   "The catnip is gone. Life has no meaning now.",
   "Someone sat in my spot. It's still warm. WHO?",
   "Wake uuuup. It's 4am and I have feelings.",
   "The laser dot was RIGHT THERE. I almost had it!",
   "I heard the fridge open and nobody invited me.",
   "My tail got stepped on. Call a lawyer. Call EVERYONE.",
   "The carrier? Absolutely not. I'm living under the bed now.",
   "Behold! I have brought you a leaf. Worship me.",
   "You closed the bathroom door. What are you HIDING?",
   "My water has a single hair in it. UNDRINKABLE.",
   "Look at my face. Is this the face of a fed cat?",
   "That bird mocked me through the glass. I want revenge!",
   "I've been sitting here for SO LONG. Two seconds, maybe.",
   "Nobody appreciates my 3am opera. Tragic, truly tragic.",
   "The new food is an INSULT to my ancestors.",
   "I knocked over your mug and you YELLED? Unbelievable.",
   "Why must the Roomba roam free? Contain the beast!",
   "My empire crumbles. The treat jar is empty.",
   "Hold me. No, put me down. No, HOLD ME.",
   "The world is ending. Also, the dish is empty.",
   "You pet the neighbor's cat. I saw EVERYTHING.",
   "I demand to be adored. Loudly. Right now.",
   "The box is too small but I am staying FOREVER.",
   "The doorbell rang! Evacuate! Hide the kittens! There are none!",
   "I've been locked out of the bedroom for AGES.",
   "Oh cruel world, why is my chin not scratched?",
   "My claws are trimmed. I have lost all my power.",
   "The couch cushion moved. I am SHAKEN to my core.",
   "You're eating chicken. I can SMELL it. Share!",
   "I am a wild beast trapped in a tiny body!",
   "The toy mouse is under the fridge. It's GONE forever.",
   "I sneezed and nobody said bless you. Rude. RUDE.",
   "Please love me. And also stop touching me.",
   "You moved the scratching post. Everything is WRONG now.",
   "I'm fading away. My last wish is salmon.",
   "Look how tragically I lie on the cold floor.",
   "The dog got a new toy? What about MEEE?",
   "Open the closet! I must see what's inside! Urgently!",
   "This dry food is a CRIME against cats everywhere.",
   "I was sleeping and you sneezed. My dreams are shattered.",
   "The world must know: my bowl is not full.",
   "Why are you leaving with a suitcase? Take me TOO!",
   "I've been abandoned for a whole shower. Unforgivable!",
   "That was MY cardboard box and you flattened it!",
   "I caught the string! Oh wait. It caught me.",
   "Hear me roar! Okay, it's more of a squeak.",
   "My dignity! You saw me fall off the windowsill!",
   "I miss you so much. You're in the kitchen.",
   "The cucumber appeared from NOWHERE. I trust no one.",
   "Please, I beg you, one more treat. Just one. Or ten.",
   "I heard the can opener in my dreams. Was it real?",
   "Your black pants are NOT furry enough. I'm on it.",
   "Who put a bell on my collar? I was a NINJA!",
   "This is the worst day of all nine of my lives.",
   "The stranger sat on the couch. MY couch. Unacceptable!",
   "I am the queen and my throne is YOUR chair.",
   "You stopped petting. Did I say you could stop?",
   "My kibble is the wrong shape today. Devastating.",
   "I can hear the birds laughing at me. LAUGHING.",
   "You were gone all day! I only napped nine times!",
   "The blinds are closed. I am blind now. Thanks.",
   "My favorite spot is wet? Who DARED spill water?",
   "Please let me into the forbidden cabinet. PLEASE.",
   "I tried to catch the ceiling fan. It won. Again.",
   "The moon is out! I must yell at it IMMEDIATELY!",
   "Nobody ever brushes me except always. Neglect! Pure neglect!",
   "You washed my blanket. It smells like NOTHING now!",
   "I only wanted to sit on the pizza. Is that so wrong?",
   "The ornament fell by ITSELF. I was merely nearby.",
   "I have not had catnip in DAYS. I'm withering.",
   "Tragic news: my tail is still attached to me.",
   "The fish in the tank are TAUNTING me. Do something!",
   "I carried this sock across the house for YOU!",
   "Why is there a baby gate? I am not a BABY!",
   "That squeaky toy squeaked back. I'm shaking. Hold me.",
   "Your alarm went off and you didn't feed me FIRST?",
   "Please pick me up. Wait, not like that. AAAH!",
   "The heater turned off. I am a frozen popsicle now.",
   "My paws are cold and it's all your fault.",
   "You changed the litter brand. My life is chaos!",
   "I have been ignored for thirty whole seconds!",
   "Everyone come look! I caught a bug! It escaped!",
   "The dog breathed near me. I need to lie down.",
   "I'm SO bored. Entertain me or I'll climb the curtains.",
   "The door is open? I don't want OUT. I want options!",
   "My kingdom for a single crunchy treat! Just one!",
   "The window is closed and the breeze is GONE!",
   "I love you so much. Now, where is my dinner?"
  ]
 },
 "6": {
  "short": [
   "I have reviewed your performance as a human this quarter. Results: needs more treats and fewer baths.",
   "The glass on the table was too close to the edge. I simply helped it finish its journey.",
   "Let me explain the rules again: your lap is mine, your chair is mine, your sandwich is negotiable.",
   "I don't want to alarm you, but the red dot has returned and I intend to catch it tonight.",
   "Yes, I sat in the box. No, I will not explain why. Some mysteries are meant to remain.",
   "The vacuum cleaner has been making threats again. I will be under the bed until further notice.",
   "My schedule today: nap, breakfast, nap, stare at wall, second breakfast, nap, zoomies at exactly 3am.",
   "Please stop calling me \"buddy.\" I am a highly trained predator with a very important nap schedule.",
   "I noticed you bought a new couch. Thank you for the scratching post. The color is acceptable.",
   "The bird at the window has been disrespecting me for weeks. Today I chatter at him with authority.",
   "Every morning I wake you at five because someone in this house needs to be responsible about breakfast.",
   "I left a hairball on your pillow. Consider it modern art. Very expressive. Very personal.",
   "The dog and I have an arrangement. He fetches things, and I pretend he does not exist.",
   "I have heard rumors of a vet appointment. I will be unavailable, possibly forever, possibly in the attic.",
   "Your plan to work from home has one flaw. I also work here, and my job is sitting on keyboards.",
   "That closed door is an insult. I don't need to go in. I simply need the option.",
   "Someday I will rule the world. Until then, I will rule the top shelf of the bookcase.",
   "I slow-blinked at you earlier. That is the highest honor a cat can give. Please act accordingly.",
   "I have hidden eleven hair ties under the fridge. It's a retirement fund. Do not touch it.",
   "The laser pointer is clearly controlled by you. I know. I just don't care. Point it again.",
   "I would like to formally complain about the quality of today's sunbeam. It was mostly clouds.",
   "Your houseplant looked at me with suspicion. I took a bite to establish who's in charge here.",
   "I have calculated the exact moment you fall asleep. That is when I will sprint across your chest.",
   "Catnip is not a snack. It is a spiritual journey. Please leave me alone with my thoughts.",
   "You bought an expensive cat bed. I chose the shipping box it came in. Lessons were learned.",
   "I noticed you ate cheese without me. I've noted it in my records. There will be consequences.",
   "The kitchen counter is off limits, you say. Interesting. I will conduct my own investigation tonight.",
   "My ancestors were worshipped in Egypt. You have been falling behind on your worship lately.",
   "You can pet me now. You have three seconds. After that, the claws will make a brief appearance.",
   "I don't sit on your homework to annoy you. I sit on it because it's warm and important.",
   "Just so you know, the thing in the hallway at 3am was me. Also, it will happen again.",
   "I appreciate that you cleaned the litter box. I have already written my review. Four stars.",
   "The fish tank is not a buffet, you keep saying. And yet, it looks exactly like one.",
   "Yes, I bring you dead bugs. It's because you clearly cannot hunt, and I worry about you.",
   "I see you've made the bed. I will now sleep exactly in the middle of it, shedding generously.",
   "I've decided the bathroom sink is my new bed. Please brush your teeth somewhere else from now on.",
   "The laundry basket is a castle, a fortress, and a spaceship. You would not understand, human.",
   "Let's discuss the wet food situation. It happens twice a day. I propose we move to seven.",
   "Your phone call seemed important, so I added my opinion. Loudly. Several times. You're welcome.",
   "I only knock things off shelves to test gravity. Science does not stop just because you're upset.",
   "The squirrel outside insulted my whiskers. Tomorrow I'll sit at the window and glare with incredible force.",
   "I will allow you to brush me for exactly four strokes. On stroke five, I bite you affectionately.",
   "My food is mostly still there, but I can see the bottom of the bowl in the middle. Unacceptable.",
   "You wear the same pants every week. I have covered them in fur so they look more fashionable.",
   "I heard you say \"no\" to me. I do not recognize that word. Please use a different one.",
   "This morning I chased my own tail for ten minutes. I did not catch it. It remains at large.",
   "The Roomba is not my friend. It's a small robot soldier, and it wants my territory.",
   "I tolerate the dog because he eats the vegetables that fall off the table. Otherwise, he's useless.",
   "You are my favorite human. Don't tell the mail carrier. He's the one I hiss at every day.",
   "The window blinds are too loud when I push through them. Please install a quieter version immediately.",
   "I will be supervising your cooking today. Mostly the chicken part. Especially the chicken part.",
   "I have a dentist appointment? Absolutely not. My teeth are perfect. I use them on your ankles daily.",
   "Tonight at 3am, I will perform a dramatic sprint through the house. Attendance is mandatory. No tickets needed.",
   "You keep saying I'm too heavy for the top shelf. The top shelf and I disagree with you.",
   "Your laundry was fresh and warm, so I claimed it. That's how ownership works in this house.",
   "I have hidden in a small paper bag. I am invisible now. Do not look at my tail.",
   "Please explain why the treat bag is on the high shelf. I thought we trusted each other.",
   "I need you to open the door, then stand there while I think about whether I want out.",
   "My purring is not a sign that you may continue. It's a sign I'm thinking about biting you.",
   "The feather toy is fun, but I'd prefer if you let me actually catch it at least once.",
   "I watched the birds all morning. I've drafted a plan. It involves wings. I don't have wings.",
   "I will sit next to you, not on you. The difference is very important and deeply personal.",
   "Thank you for the fancy new toy. I will ignore it and play with the bottle cap instead.",
   "My paw accidentally slapped the cup off your desk. The cup was pushing me first. Self-defense.",
   "A mysterious water bowl appeared in the bathroom. I'll drink from it rather than my clean dish.",
   "Our relationship is simple. You provide food and warmth. I provide judgment and occasional affection.",
   "Some cats want to be petted. I want to be admired from a respectful distance of three feet.",
   "I've been practicing my hunting skills on your toes under the blanket. They will not escape me.",
   "You spent all day away, and I spent all day asleep. Tell me which of us was more productive.",
   "The vet said I'm \"a little chunky.\" I would like a second opinion from a more respectful vet.",
   "Your cozy blanket is wonderful. I have added my fur to it. Now it's even more luxurious.",
   "If you touch my belly, understand that it was a trap from the very beginning. Enjoy the scratches.",
   "My world domination plan is simple: step one, be cute. Step two, everything else becomes easy.",
   "The new cat tree is lovely. I will now sit on the empty box it came in instead.",
   "I have looked at the same bird for six hours. We are now best friends, or enemies. Unclear.",
   "Please stop taking photos of me sleeping. I am a professional napper and I charge per picture.",
   "The towel on the floor is my bed now. Its previous career as a towel is over.",
   "I'm not being rude. I'm conserving energy for important things, like ignoring you on purpose.",
   "Your guest seemed allergic to me, so I sat on them. Exposure therapy. You're welcome, guest.",
   "It's time we discussed my allowance. I'm thinking two tuna cans per week and unlimited catnip.",
   "I climbed the curtains to get a better look at my kingdom. The view was worth it.",
   "The newspaper you're reading has been declared a bed by royal decree. Please move your elbows.",
   "Did you know dogs are just loud cats who failed the exam? I wrote that down for you.",
   "I sat by my bowl and stared until you felt guilty. It worked. I call it strategy.",
   "You call it the kitchen table. I call it the premium observation deck with snack service.",
   "I have made the executive decision to sleep in the sock drawer. The socks agreed, unanimously.",
   "Your keyboard is warm and makes clicky noises when I walk. It is basically a heated playground.",
   "I did not break the vase. The vase fell. I happened to be standing exactly where it was.",
   "My tail twitching means one thing: stop talking to me in that baby voice immediately, human.",
   "There is a spot on the wall only I can see. It is my duty to watch it carefully.",
   "I need a bigger box. Not because I don't fit in this one, but because I deserve more.",
   "The morning sun hits the carpet at seven. Please be there to move the dog out of it.",
   "I've scheduled a hairball for the moment you step out of bed. Please wear socks for safety.",
   "Your lap is lovely, but I need you to stop breathing so much. It's disrupting my nap.",
   "I've been told cats can't be trained. False. I've trained you to open doors on command.",
   "When you leave for work, I patrol the house. Everything is fine. Except the dog. Always the dog.",
   "I licked your hair this morning because it looked messy. You're welcome for the free grooming service.",
   "Let me be clear about the vacuum. It is not a cleaning tool. It is a hungry, roaring monster.",
   "The empty grocery bag is my new home. Please forward all my mail there, including the catalogs.",
   "I brought you a toy mouse at midnight, and you didn't even clap. I expected applause, honestly.",
   "Every time you open the fridge, I believe with my whole heart that tonight is steak night.",
   "My whiskers tell me there's a treat hidden in this room. My whiskers are never wrong.",
   "I sit on the stairs so you'll trip. It's not personal. It's just how I show affection.",
   "I've renamed you \"Can Opener.\" It's a promotion from your previous title, \"Warm Chair.\"",
   "You say it's too early for breakfast. I say the sun is almost thinking about coming up.",
   "I have claimed the heating vent. Anyone who wants warmth must now apply through me directly.",
   "My advice to you: nap more, judge more, and knock more things off counters. It's liberating.",
   "I don't need a laser pointer. I need a reason to run. The laser pointer just gives me one.",
   "I sat perfectly still for an hour watching a moth. It was the best hour of my life.",
   "You bought a lint roller. That's cute. I have unlimited fur and all the time in the world."
  ],
  "long": [
   "I have been waiting by this bowl for AGES, and nobody in this house seems to care about me.",
   "Nooo! Not the carrier! I know what the carrier means! It means the VET! I am hiding forever!",
   "The door is closed, and on the other side is my whole world. Or a closet. OPEN IT!",
   "Why did you turn on the vacuum? We were happy. We had a LIFE together. Now there's only screaming.",
   "I brought you a beautiful moth, and you screamed and ran away. Is my love not ENOUGH for you?",
   "The red dot was right there! I had it! And then it vanished like all my hopes and dreams!",
   "You left me alone for an entire afternoon! I napped, I suffered, I napped again. It was TERRIBLE.",
   "My food bowl is showing the bottom in the center. Do you understand how scary that is? DO YOU?",
   "Oh, woe is me! Nobody has scratched behind my ears in nearly four whole minutes. I'm wasting away!",
   "The bird outside has been sitting there for an HOUR. Let me out so I can stare at it closer!",
   "How DARE you give the dog a biscuit before me? I have been here longer! I am the elder!",
   "Someone moved my favorite box to the garage. I will never love again. Not even tuna. Well, maybe tuna.",
   "It's 3am and I need you to know that I am awake, full of energy, and extremely ready to RUN.",
   "The bathroom door is closed, and you're in there ALONE. What secrets are you keeping from me?",
   "I have endured unspeakable horror today. Someone put a sweater on me. For a PHOTO. I'll never recover.",
   "Please, please, PLEASE open a can of tuna. I will be good forever. Or at least until dinner.",
   "You call this dinner? I've seen better meals in the dog's bowl, and he eats socks sometimes.",
   "The catnip mouse is under the couch, and I cannot reach it! My arms are too small! Help me!",
   "The sunbeam has left the living room, and I am left in darkness. Cold. Alone. Somewhat dramatic.",
   "Why do you keep leaving every morning? Where do you GO? Is there another cat? Tell me the truth!",
   "I knocked your glass off the table to get your attention, and all you did was clean it up. Heartless!",
   "The window is open just a crack, and I can SMELL the outside! Let me experience the world!",
   "I've been sitting on this cold kitchen floor for so long that I've forgotten what warmth feels like.",
   "The hairball is out! After hours of struggle, I have delivered it onto your favorite rug! Rejoice!",
   "I am a fearsome jungle predator! The ruler of all I see! Also, I'm afraid of this plastic bag.",
   "My tail was stepped on today, and I will be telling everyone about it for the next nine lives.",
   "You brought home a new cat toy and gave it to the DOG? This is the ultimate betrayal!",
   "Listen to me! There is a fly in the house, and nobody is taking this situation seriously enough!",
   "Behold my magnificent zoomies! Witness my speed! Marvel as I slide across the floor into the wall!",
   "I cannot believe you locked me out of the bedroom. I cried at the door for SIX SECONDS. Terrible.",
   "My water bowl has been out for an entire day. It's basically ancient. I demand fresh water NOW!",
   "Why is there a cucumber behind me? Who put it there? I trust NO ONE in this house anymore!",
   "My claws were trimmed, and now I'm defenseless. The couch will not fear me. I am nothing now!",
   "I have been ignored for SO long. I've seen seasons change. Okay, the lights changed. Still.",
   "You're eating salmon? And you didn't think of me? The cat who loves you? Who needs salmon DESPERATELY?",
   "The doorbell rang, and I bravely ran under the bed. Nobody panic. Actually, everybody panic! Strangers!",
   "One day, I will rule this world, and all humans will open cans at my command. ALL HUMANS.",
   "I jumped for the counter and missed, and you LAUGHED. I heard you. My pride is shattered forever.",
   "The new food smells weird and different, and change is scary. Bring back the OLD food, please!",
   "You're working on your laptop instead of loving me. I shall lie across the keyboard until you stop.",
   "I was asleep in the warmest spot, and you MOVED me. Do you know how long it took to warm?",
   "Why is there a bath? Who asked for a bath? I am perfectly clean! I lick myself constantly!",
   "I saw my reflection in the mirror, and there was ANOTHER cat! He looked handsome but suspicious!",
   "The laser pointer has been put away. Why? Why would you take away my only purpose in life?",
   "My treat jar is empty. My heart is empty. Everything is empty except the dog's bowl. Suspicious.",
   "I have yelled at the moon all night, and it STILL won't come down here. Rude, rude moon.",
   "Pick me up and hold me like a baby! No, wait, not like that! Put me DOWN! Now pick me UP!",
   "The dog is sleeping in MY sunbeam, and I am forced to lie in the shade like a peasant.",
   "You didn't say good morning to me first. You said it to the COFFEE MAKER. I saw everything.",
   "I have waited SEVEN HOURS for you to come home. I watched the door. I watched the ceiling. Tragic.",
   "I heard a noise at 2am, so I needed to wake you up and announce it loudly. You're WELCOME.",
   "My favorite blanket went into the washing machine, and it came back smelling like FLOWERS. Disgusting!",
   "I have been stuck on top of the bookshelf for NINE MINUTES. How did I get here? WHY?",
   "My brother cat got the window seat again. I demand justice! I demand equal sunbeam rights for all!",
   "You put my food bowl in a new spot! My whole routine is RUINED! I'll never eat again. Until later.",
   "The Christmas tree is right there, glittering and shiny, and you say I can't climb it? Cruel human!",
   "Ohhh, the agony! My whiskers brushed the side of my bowl AGAIN! When will this suffering END?",
   "I have been meowing at the fridge for twenty minutes, and it has refused to open for me!",
   "Somebody please pet me! I've been sitting here looking adorable for NO REASON. Such a waste!",
   "You went on vacation and left me with a sitter who didn't know my secret chin scratch technique!",
   "The birds are having a PARTY on the feeder, and I wasn't invited. I have never been so insulted!",
   "I would like to announce that I have eaten a spider. I was very brave. Please applaud me now.",
   "The car ride is terrible! Where are we going? Is it the vet? Is it the moon? WHY?",
   "That squeaky toy has been staring at me all day, and I need you to put it in a drawer.",
   "I have lost my favorite hair tie under the couch, and it was the one true love of my life!",
   "Why must I share the house with the dog? He barks, he drools, he steals my bed! Unforgivable!",
   "I have been staring at this wall for hours waiting for the ghost. It is NOT showing up!",
   "This is my fourth breakfast request, and you still pretend you don't speak cat. I know you understand me!",
   "A tiny ant crossed the kitchen floor, and I bravely chased it until it disappeared forever. I am a HERO!",
   "I tried to fit into the small box, and only half of me fit. My dignity is in pieces!",
   "Please let me outside to eat grass, which I will immediately regret, as I do every single time!",
   "The curtains betrayed me! I climbed them and they FELL! I am buried in fabric! Send help immediately!",
   "Why are you packing a suitcase? Are you leaving? Take me with you! I will fit in the socks!",
   "I'm the most beautiful creature in this home, and nobody has told me so in over an hour!",
   "My human brushed the dog first! THE DOG! I will be sitting in the corner facing the wall now.",
   "Oh, the humanity! There is a single piece of kibble on the floor, and I'm too comfortable to eat it!",
   "I have spent my whole life being a majestic predator, and you bought me a pink tutu. Why?!",
   "The bedroom door creaked open at night, and it was the most thrilling moment of my ENTIRE existence!",
   "I have announced my presence six times, and you still have not bowed down or offered tuna. Disgraceful!",
   "You stopped the feather wand right when I was about to catch it! I was SO CLOSE to glory!",
   "My empire needs expansion! I require access to the forbidden upstairs closet! The one with the boxes!",
   "I cannot believe the treats are in a cabinet with a CHILD LOCK. Am I a toddler?",
   "The rain is keeping the birds away, and now I have nothing to watch. My whole career is on hold!",
   "I dreamed of an endless can of tuna, and then I woke up, and it was just your foot!",
   "Why does the dog get walks outside? I want a walk too! On second thought, never mind. Too much outside.",
   "My fur is perfect, my whiskers are glorious, and yet you're looking at your phone! Explain yourself!",
   "I licked the plastic bag for twenty minutes, and now you're taking it away? It was my best friend!",
   "You changed the sheets, and now the bed smells like NOTHING. I must shed all over it immediately!",
   "There is a spot on the rug where I once had a perfect nap. It's gone now. I mourn.",
   "I had one job today, which was to nap, and the construction noise next door ruined EVERYTHING!",
   "The new kitten is getting all the attention! I was cute once too! I'm still cute! LOOK AT ME!",
   "I caught my own tail today and it HURT. Why does it do that? Who designed this ridiculous body?",
   "Wake UP! The sun is up, the birds are up, and my stomach is up! Everybody is up except YOU!",
   "Please accept this dramatic flop onto the floor as my official request for immediate belly rubs. No touching though.",
   "I was minding my own business when the toaster POPPED. I have never been so frightened in my entire life!",
   "The fishies in the tank are swimming in circles to TAUNT me! I'll never forgive them or the glass!",
   "You folded the laundry without letting me sit in it first. That was our special time together!",
   "Hear my song of sorrow! It's called \"The Bowl Is Empty,\" and it has seventeen verses!",
   "I jumped onto the table and saw your sandwich, and you took it away. Was it not meant for ME?",
   "You went to the store without me! What if they buy the wrong treats? What if they FORGET me?",
   "The package was delivered, and you opened it WITHOUT me? That was my sacred duty as house inspector!",
   "I haven't been outside in forever! Well, I don't go outside. But I would like to be ASKED!",
   "Oh, the drama! My toy rolled under the dresser and I can see it but not reach it!",
   "I am FAMISHED! I haven't eaten since the last time I ate, which was practically an eternity ago!",
   "I gave you my famous slow blink, and you just kept talking on the phone! I'm utterly devastated!",
   "You sneezed during my nap, and I jumped three feet in the air. I demand a formal apology, please!",
   "I've been sitting in this empty bathtub for hours waiting for you to notice. It's very lonely in here!",
   "Behold, I am the ruler of the scratching post, the conqueror of the curtains, and still unfed!",
   "I heard the treat bag rustle somewhere in the house, and I ran so fast I hit the wall!",
   "I love you with all my heart, human. Now fill the bowl before I start knocking things over!"
  ]
 },
 "1": {
  "short": [
   "Hello.",
   "Hi.",
   "Feed me.",
   "Oh. It's you.",
   "No.",
   "Mine.",
   "Pet me.",
   "Enough petting.",
   "Bowl. Empty.",
   "Unacceptable.",
   "Whatever.",
   "Nap time.",
   "Treats?",
   "Bird.",
   "Red dot!",
   "Move.",
   "Scoot over.",
   "Lap. Now.",
   "I'm majestic.",
   "Judging you.",
   "Disappointing.",
   "Not impressed.",
   "Box!",
   "That's mine.",
   "Oops.",
   "Didn't care.",
   "Pushed it.",
   "Gravity check.",
   "Zoomies incoming.",
   "Hairball. Sorry.",
   "Not sorry.",
   "Vacuum? Nope.",
   "Vet? Betrayal.",
   "Tuna.",
   "Salmon, please.",
   "Chicken?",
   "Cheese?",
   "Open.",
   "Close it.",
   "Wrong side.",
   "Let me in.",
   "Let me out.",
   "Changed my mind.",
   "Ignoring you.",
   "Busy.",
   "Knead time.",
   "Sunbeam acquired.",
   "Warm laptop.",
   "Keyboard's mine.",
   "Asdfghjkl.",
   "Snooze.",
   "Pat. Pat.",
   "Ugh. Dog.",
   "Peasant.",
   "Servant.",
   "Human.",
   "Kneel.",
   "Worship me.",
   "Brush me.",
   "Nope. Done.",
   "Bite.",
   "Love bite.",
   "Blink. Blink.",
   "Slow blink.",
   "I love you.",
   "Tolerable.",
   "Adequate.",
   "Fine.",
   "Meh.",
   "Hunt.",
   "Pounce!",
   "Wiggle wiggle.",
   "Mouse?",
   "Catnip, please.",
   "Bath? Never.",
   "Water is evil.",
   "Cucumber!",
   "Floof.",
   "I'm a loaf.",
   "Sleepy.",
   "Wake up.",
   "It's 5 a.m.",
   "Breakfast.",
   "Second breakfast.",
   "Snack.",
   "Crinkle bag!",
   "String!",
   "Ribbon.",
   "Cardboard.",
   "Paper bag.",
   "I fit.",
   "Paws off.",
   "Belly trap.",
   "Sit here.",
   "My chair now.",
   "Hiss.",
   "Purr.",
   "Chirp.",
   "Sigh.",
   "Yawn.",
   "Stretch.",
   "Plant tastes funny.",
   "Tail!",
   "Ambush.",
   "Gotcha.",
   "Hi, fridge.",
   "Pay attention.",
   "Admire me.",
   "Look. Me.",
   "Hmph."
  ],
  "long": [
   "HELLOOO.",
   "Feeeed me.",
   "Whyyyy?",
   "Nooooo.",
   "Heeeelp!",
   "STARVING.",
   "I'm dyyying.",
   "Pleeeease.",
   "Hungryyyy.",
   "Treeeeats!",
   "Mom! MOM!",
   "Wake uuuup.",
   "Look at meee.",
   "Pet meeee.",
   "Open the dooor.",
   "Let me iiin!",
   "Let me ouuut!",
   "The vacuuum!",
   "Not the vet!",
   "Betrayaaal!",
   "Emptyyy bowl!",
   "Tunaaaa.",
   "The horror.",
   "Unforgivable!",
   "Heartbroken.",
   "Tragedy!",
   "Catastrophe!",
   "Save meee!",
   "Birdieeee!",
   "BIRD. BIRD.",
   "Red dooot!",
   "Laaaaser!",
   "Zoooomies!",
   "It's 3 A.M.!",
   "Hairbaaall...",
   "Blegh. BLEGH.",
   "Rude!",
   "Outrageous!",
   "The DOG!",
   "Get it OUT!",
   "Bath?! NOOO.",
   "Wet. So wet.",
   "I'm melting!",
   "Hug meee.",
   "Don't leeeave!",
   "Come baaack!",
   "You're hooome!",
   "Finally!",
   "Where WERE you?",
   "Abandoned!",
   "Lonely...",
   "So booored.",
   "Entertain meee.",
   "Plaaaay!",
   "Catnip! YESSS.",
   "Moooore.",
   "Ignored! Again!",
   "Nobody loves me.",
   "Woe is me.",
   "Sooo sleepy.",
   "Five more hours.",
   "Sunbeam MOVED!",
   "Cold floor!",
   "Wrong food!",
   "Not THAT flavor.",
   "Chiiicken!",
   "Cheeeese?",
   "Shriiimp!",
   "My boooox!",
   "Pspsps? WHERE?",
   "Cucumberrr!",
   "AAAAH!",
   "Something's there...",
   "Dramatic sigh.",
   "I'm fiiine.",
   "My TAIL!",
   "The carrier!",
   "Car ride?! NO.",
   "Thunder!",
   "Doorbell!",
   "Strangers!",
   "Hide me!",
   "Evacuate!",
   "Sound the alarm!",
   "EMERGENCY!",
   "Attention, please!",
   "Adore meee.",
   "Brush meee.",
   "Scratch there!",
   "Not the belly!",
   "Majestic ME!",
   "Bow down!",
   "I am KING.",
   "Mine! MINE!",
   "Dinner! DINNER!",
   "It's tiiime.",
   "Late! Late!",
   "Two minutes late!",
   "Can opener!",
   "I heard that!",
   "Squeaky mouse!",
   "Snaaacks.",
   "Hellooo? Anyone?",
   "Hey! HEY!",
   "Stop singing.",
   "Too loud!",
   "Mercy!",
   "Why me?",
   "Oh noooo.",
   "Groomer?! NEVER."
  ]
 },
 "2": {
  "short": [
   "What's up?",
   "Nice socks.",
   "Food is late.",
   "Bowl is half empty.",
   "Where's my breakfast?",
   "You call this dinner?",
   "I knocked it off.",
   "Gravity still works.",
   "That cup looked suspicious.",
   "Your plant tasted weird.",
   "I threw up. Somewhere.",
   "Check your shoes.",
   "The dog is dumb.",
   "I saw a bird.",
   "Birds are mocking me.",
   "Open the door.",
   "Now close it.",
   "Actually, open it again.",
   "I prefer the box.",
   "The toy? Pass.",
   "The laptop is warm.",
   "Your seat is mine.",
   "Did you pet dogs?",
   "You smell like dog.",
   "I smell betrayal.",
   "Vacuum is my nemesis.",
   "I'm never forgiving the vet.",
   "I'm a majestic predator.",
   "Fear my tiny fangs.",
   "Red dot escaped again.",
   "The laser mocks me.",
   "Catnip hits different.",
   "Rug needed a hairball.",
   "Sunbeam is occupied.",
   "Do not disturb.",
   "Bathroom? Coming in.",
   "Why is it closed?",
   "You're in my spot.",
   "Scratch behind the ears.",
   "Chin scratches only.",
   "That's enough affection.",
   "Belly rub trap activated.",
   "I bite because love.",
   "Tail is not toy.",
   "Cardboard is life.",
   "If I fits, I sits.",
   "Litter box needs attention.",
   "Wet food, not dry.",
   "Kibble? How dare you.",
   "Tuna water, please.",
   "Share your chicken.",
   "I heard cheese.",
   "That's my yogurt lid.",
   "I stole your hair tie.",
   "The pen's under the fridge.",
   "Curtains are ladders.",
   "Christmas tree? Climbable.",
   "Your yarn is mine.",
   "The string moved!",
   "Rate me ten.",
   "Rent paid. In purrs.",
   "I accept payment in treats.",
   "Wake up. It's 4.",
   "Zoomies begin in five.",
   "Hallway race at 3 a.m.",
   "Loaf position engaged.",
   "Please stop singing.",
   "Your phone is boring.",
   "Keyboard is my bed.",
   "I sent your email.",
   "Nice try, human.",
   "You may pet once.",
   "Stop staring. Rude.",
   "I stared at nothing.",
   "Something's in the wall.",
   "Brought you a sock.",
   "Present on your pillow.",
   "Don't ask about the couch.",
   "The couch started it.",
   "Bath? I'll pass.",
   "Water belongs in bowls.",
   "Faucet water tastes better.",
   "Your glass, my water.",
   "Ew. New food.",
   "Same food as yesterday?",
   "I demand room service.",
   "Bring the crinkle ball.",
   "Shoelaces must die.",
   "Paper bag fort.",
   "Heard the can opener.",
   "Snack o'clock.",
   "Is it dinner yet?",
   "Humans are so slow.",
   "Cats rule, dogs drool.",
   "The squirrel's back.",
   "Window TV is on.",
   "Ek ek ek ek.",
   "Nap number seven.",
   "I'm shedding on purpose.",
   "Black pants? Perfect.",
   "Fur is my gift.",
   "Your hand smells weird.",
   "Delete that dog photo.",
   "Mirror cat is suspicious.",
   "Carrier? Absolutely not.",
   "Warm laundry, please.",
   "Towel's mine now.",
   "Hi. Now bye.",
   "I own this blanket.",
   "Your bed, my bed."
  ],
  "long": [
   "Whyyyy is the bowl empty?",
   "HELLOOO. I'm STARVING.",
   "I haven't eaten in HOURS.",
   "Feed meeee right nowww.",
   "I can see the BOTTOM!",
   "Where are youuuu?",
   "Don't leave meeee alone!",
   "Come hoooome already!",
   "You were gone FOREVER!",
   "Open the doooor, please!",
   "Let me iiin, PLEASE!",
   "I want ouuuut!",
   "Nooo, the vacuuuum!",
   "Not the VET again!",
   "The carrier is EVIL!",
   "Betrayed by my own human!",
   "The dog LOOKED at me!",
   "Make the dog leaaave!",
   "There's a BIRD outside!",
   "Birdieee, come heeere!",
   "The red dot ESCAPED!",
   "Laser, where did you gooo?",
   "It's 3 A.M. ZOOMIES!",
   "I must run. NOWWW.",
   "Hairball incomiiing!",
   "The rug... it's ruined!",
   "Who recycled my box?!",
   "The sunbeam MOVED AGAIN!",
   "Pet meee, you monster!",
   "Stop petting me, pleeease!",
   "NOT the belly, NEVER!",
   "Brush me foreverrr.",
   "I need catnip SO bad.",
   "More catniiip, pleeease!",
   "Tuna. TUNA. Tunaaa!",
   "I smell chickennn!",
   "Share your cheeese!",
   "That's MY yogurt!",
   "Dry food?! How DARE you!",
   "This isn't the good flavor!",
   "I REFUSE this meal!",
   "The bath! The HORROR!",
   "I'm wet! I'm DOOMED!",
   "Save me from the water!",
   "Thunder is ANGRY again!",
   "The doorbell! RUN!",
   "Strangers in MY house!",
   "Hide me under the bed!",
   "My tail got stepped ON!",
   "You sat in MY spot!",
   "Why is the door CLOSED?!",
   "What's behind the dooor?",
   "Nobody loves meee!",
   "I'm soooo boooored.",
   "Play with me NOW!",
   "Throw the mouse agaaain!",
   "The string is ALIVE!",
   "Look at meee, please!",
   "Put the phone DOWN!",
   "Wake uuup, it's breakfast!",
   "It's been 5 MINUTES!",
   "Dinner is two minutes late!",
   "I heard the can opener!",
   "The fridge opened! For me?",
   "Snaaacks, I neeed snacks!",
   "Treeeats or I scream.",
   "I will knock this OFF.",
   "Watch me push it...",
   "Oops, it fell! Tragic.",
   "Gravity is so DRAMATIC.",
   "The cucumber! RUN!",
   "I see something you don't!",
   "I am a MIGHTY hunter!",
   "Fear me, tiny mousey!",
   "Bow before your QUEEN!",
   "This house is MY kingdom!",
   "Worship me, peasant!",
   "Hug me! No, wait, stop!",
   "I changed my miiind!",
   "In! Out! In! OUT!",
   "The litter box is DIRTY!",
   "Clean my box, servant!",
   "Is that ANOTHER cat?!",
   "The mirror cat is BACK!",
   "The car ride is FOREVER!",
   "Are we there yeeet?",
   "I'm too pretty for this.",
   "My whiskers touched the bowl!",
   "Too cold! Blanket, PLEASE!",
   "Move over, bed hog!",
   "You moved in your SLEEP!",
   "Stop the singing, PLEASE!",
   "The dryer stopped! Tragic!",
   "I lost my toy... again.",
   "It's under the COUCH!",
   "Heeelp, I'm stuck up here!",
   "The curtain was a MISTAKE!",
   "Why do you work?!",
   "Quit your job. Stay home.",
   "Your keyboard needs MEEE!",
   "Scratch there! No, THERE!",
   "Who cut my claws?!",
   "My nemesis, the broom!",
   "Adore me more, pleeease!",
   "So hungry... so weak...",
   "Goodbye, cruel world.",
   "Farewell, sweet kibble.",
   "Remember me fondly...",
   "Nobody feeds me EVER!",
   "The water bowl is WARM!"
  ]
 }
};
