// Cat-to-English phrase book: CAT_PHRASES[meowCount]["short" | "long"].
// "short" = normal meows, "long" = drawn-out meows. 6 means 6 or more.
window.CAT_PHRASES = {
 "3": {
  "short": [
   "I like mice.",
   "Where's my dinner?",
   "I love you. Barely.",
   "That's my chair.",
   "I saw a bird."
  ]
 },
 "4": {
  "short": [
   "The red dot got away again.",
   "Your laptop is my bed now.",
   "I knocked it off on purpose.",
   "Open the door. No, the other one."
  ]
 },
 "5": {
  "short": [
   "I would like to file a complaint about the bottom of my food bowl.",
   "I have been starving for eleven minutes.",
   "Please clean my litter box. I have standards."
  ]
 },
 "6": {
  "short": [
   "Your 3 a.m. wake-up call is non-negotiable.",
   "I have decided the box is better than the gift.",
   "Listen carefully. I am the landlord now, and rent is due in tuna.",
   "My lawyer, Mr. Whiskers, will be in touch about the vacuum cleaner."
  ]
 },
 "1": {
  "short": [
   "Hello.",
   "Hi.",
   "Feed me.",
   "Oh. It's you.",
   "No.",
   "Mine.",
   "Pet me.",
   "Enough petting.",
   "Bowl. Empty.",
   "Unacceptable.",
   "Whatever.",
   "Nap time.",
   "Treats?",
   "Bird.",
   "Red dot!",
   "Move.",
   "Scoot over.",
   "Lap. Now.",
   "I'm majestic.",
   "Judging you.",
   "Disappointing.",
   "Not impressed.",
   "Box!",
   "That's mine.",
   "Oops.",
   "Didn't care.",
   "Pushed it.",
   "Gravity check.",
   "Zoomies incoming.",
   "Hairball. Sorry.",
   "Not sorry.",
   "Vacuum? Nope.",
   "Vet? Betrayal.",
   "Tuna.",
   "Salmon, please.",
   "Chicken?",
   "Cheese?",
   "Open.",
   "Close it.",
   "Wrong side.",
   "Let me in.",
   "Let me out.",
   "Changed my mind.",
   "Ignoring you.",
   "Busy.",
   "Knead time.",
   "Sunbeam acquired.",
   "Warm laptop.",
   "Keyboard's mine.",
   "Asdfghjkl.",
   "Snooze.",
   "Pat. Pat.",
   "Ugh. Dog.",
   "Peasant.",
   "Servant.",
   "Human.",
   "Kneel.",
   "Worship me.",
   "Brush me.",
   "Nope. Done.",
   "Bite.",
   "Love bite.",
   "Blink. Blink.",
   "Slow blink.",
   "I love you.",
   "Tolerable.",
   "Adequate.",
   "Fine.",
   "Meh.",
   "Hunt.",
   "Pounce!",
   "Wiggle wiggle.",
   "Mouse?",
   "Catnip, please.",
   "Bath? Never.",
   "Water is evil.",
   "Cucumber!",
   "Floof.",
   "I'm a loaf.",
   "Sleepy.",
   "Wake up.",
   "It's 5 a.m.",
   "Breakfast.",
   "Second breakfast.",
   "Snack.",
   "Crinkle bag!",
   "String!",
   "Ribbon.",
   "Cardboard.",
   "Paper bag.",
   "I fit.",
   "Paws off.",
   "Belly trap.",
   "Sit here.",
   "My chair now.",
   "Hiss.",
   "Purr.",
   "Chirp.",
   "Sigh.",
   "Yawn.",
   "Stretch.",
   "Plant tastes funny.",
   "Tail!",
   "Ambush.",
   "Gotcha.",
   "Hi, fridge.",
   "Pay attention.",
   "Admire me.",
   "Look. Me.",
   "Hmph."
  ],
  "long": [
   "HELLOOO.",
   "Feeeed me.",
   "Whyyyy?",
   "Nooooo.",
   "Heeeelp!",
   "STARVING.",
   "I'm dyyying.",
   "Pleeeease.",
   "Hungryyyy.",
   "Treeeeats!",
   "Mom! MOM!",
   "Wake uuuup.",
   "Look at meee.",
   "Pet meeee.",
   "Open the dooor.",
   "Let me iiin!",
   "Let me ouuut!",
   "The vacuuum!",
   "Not the vet!",
   "Betrayaaal!",
   "Emptyyy bowl!",
   "Tunaaaa.",
   "The horror.",
   "Unforgivable!",
   "Heartbroken.",
   "Tragedy!",
   "Catastrophe!",
   "Save meee!",
   "Birdieeee!",
   "BIRD. BIRD.",
   "Red dooot!",
   "Laaaaser!",
   "Zoooomies!",
   "It's 3 A.M.!",
   "Hairbaaall...",
   "Blegh. BLEGH.",
   "Rude!",
   "Outrageous!",
   "The DOG!",
   "Get it OUT!",
   "Bath?! NOOO.",
   "Wet. So wet.",
   "I'm melting!",
   "Hug meee.",
   "Don't leeeave!",
   "Come baaack!",
   "You're hooome!",
   "Finally!",
   "Where WERE you?",
   "Abandoned!",
   "Lonely...",
   "So booored.",
   "Entertain meee.",
   "Plaaaay!",
   "Catnip! YESSS.",
   "Moooore.",
   "Ignored! Again!",
   "Nobody loves me.",
   "Woe is me.",
   "Sooo sleepy.",
   "Five more hours.",
   "Sunbeam MOVED!",
   "Cold floor!",
   "Wrong food!",
   "Not THAT flavor.",
   "Chiiicken!",
   "Cheeeese?",
   "Shriiimp!",
   "My boooox!",
   "Pspsps? WHERE?",
   "Cucumberrr!",
   "AAAAH!",
   "Something's there...",
   "Dramatic sigh.",
   "I'm fiiine.",
   "My TAIL!",
   "The carrier!",
   "Car ride?! NO.",
   "Thunder!",
   "Doorbell!",
   "Strangers!",
   "Hide me!",
   "Evacuate!",
   "Sound the alarm!",
   "EMERGENCY!",
   "Attention, please!",
   "Adore meee.",
   "Brush meee.",
   "Scratch there!",
   "Not the belly!",
   "Majestic ME!",
   "Bow down!",
   "I am KING.",
   "Mine! MINE!",
   "Dinner! DINNER!",
   "It's tiiime.",
   "Late! Late!",
   "Two minutes late!",
   "Can opener!",
   "I heard that!",
   "Squeaky mouse!",
   "Snaaacks.",
   "Hellooo? Anyone?",
   "Hey! HEY!",
   "Stop singing.",
   "Too loud!",
   "Mercy!",
   "Why me?",
   "Oh noooo.",
   "Groomer?! NEVER."
  ]
 },
 "2": {
  "short": [
   "What's up?",
   "Nice socks.",
   "Food is late.",
   "Bowl is half empty.",
   "Where's my breakfast?",
   "You call this dinner?",
   "I knocked it off.",
   "Gravity still works.",
   "That cup looked suspicious.",
   "Your plant tasted weird.",
   "I threw up. Somewhere.",
   "Check your shoes.",
   "The dog is dumb.",
   "I saw a bird.",
   "Birds are mocking me.",
   "Open the door.",
   "Now close it.",
   "Actually, open it again.",
   "I prefer the box.",
   "The toy? Pass.",
   "The laptop is warm.",
   "Your seat is mine.",
   "Did you pet dogs?",
   "You smell like dog.",
   "I smell betrayal.",
   "Vacuum is my nemesis.",
   "I'm never forgiving the vet.",
   "I'm a majestic predator.",
   "Fear my tiny fangs.",
   "Red dot escaped again.",
   "The laser mocks me.",
   "Catnip hits different.",
   "Rug needed a hairball.",
   "Sunbeam is occupied.",
   "Do not disturb.",
   "Bathroom? Coming in.",
   "Why is it closed?",
   "You're in my spot.",
   "Scratch behind the ears.",
   "Chin scratches only.",
   "That's enough affection.",
   "Belly rub trap activated.",
   "I bite because love.",
   "Tail is not toy.",
   "Cardboard is life.",
   "If I fits, I sits.",
   "Litter box needs attention.",
   "Wet food, not dry.",
   "Kibble? How dare you.",
   "Tuna water, please.",
   "Share your chicken.",
   "I heard cheese.",
   "That's my yogurt lid.",
   "I stole your hair tie.",
   "The pen's under the fridge.",
   "Curtains are ladders.",
   "Christmas tree? Climbable.",
   "Your yarn is mine.",
   "The string moved!",
   "Rate me ten.",
   "Rent paid. In purrs.",
   "I accept payment in treats.",
   "Wake up. It's 4.",
   "Zoomies begin in five.",
   "Hallway race at 3 a.m.",
   "Loaf position engaged.",
   "Please stop singing.",
   "Your phone is boring.",
   "Keyboard is my bed.",
   "I sent your email.",
   "Nice try, human.",
   "You may pet once.",
   "Stop staring. Rude.",
   "I stared at nothing.",
   "Something's in the wall.",
   "Brought you a sock.",
   "Present on your pillow.",
   "Don't ask about the couch.",
   "The couch started it.",
   "Bath? I'll pass.",
   "Water belongs in bowls.",
   "Faucet water tastes better.",
   "Your glass, my water.",
   "Ew. New food.",
   "Same food as yesterday?",
   "I demand room service.",
   "Bring the crinkle ball.",
   "Shoelaces must die.",
   "Paper bag fort.",
   "Heard the can opener.",
   "Snack o'clock.",
   "Is it dinner yet?",
   "Humans are so slow.",
   "Cats rule, dogs drool.",
   "The squirrel's back.",
   "Window TV is on.",
   "Ek ek ek ek.",
   "Nap number seven.",
   "I'm shedding on purpose.",
   "Black pants? Perfect.",
   "Fur is my gift.",
   "Your hand smells weird.",
   "Delete that dog photo.",
   "Mirror cat is suspicious.",
   "Carrier? Absolutely not.",
   "Warm laundry, please.",
   "Towel's mine now.",
   "Hi. Now bye.",
   "I own this blanket.",
   "Your bed, my bed."
  ],
  "long": [
   "Whyyyy is the bowl empty?",
   "HELLOOO. I'm STARVING.",
   "I haven't eaten in HOURS.",
   "Feed meeee right nowww.",
   "I can see the BOTTOM!",
   "Where are youuuu?",
   "Don't leave meeee alone!",
   "Come hoooome already!",
   "You were gone FOREVER!",
   "Open the doooor, please!",
   "Let me iiin, PLEASE!",
   "I want ouuuut!",
   "Nooo, the vacuuuum!",
   "Not the VET again!",
   "The carrier is EVIL!",
   "Betrayed by my own human!",
   "The dog LOOKED at me!",
   "Make the dog leaaave!",
   "There's a BIRD outside!",
   "Birdieee, come heeere!",
   "The red dot ESCAPED!",
   "Laser, where did you gooo?",
   "It's 3 A.M. ZOOMIES!",
   "I must run. NOWWW.",
   "Hairball incomiiing!",
   "The rug... it's ruined!",
   "Who recycled my box?!",
   "The sunbeam MOVED AGAIN!",
   "Pet meee, you monster!",
   "Stop petting me, pleeease!",
   "NOT the belly, NEVER!",
   "Brush me foreverrr.",
   "I need catnip SO bad.",
   "More catniiip, pleeease!",
   "Tuna. TUNA. Tunaaa!",
   "I smell chickennn!",
   "Share your cheeese!",
   "That's MY yogurt!",
   "Dry food?! How DARE you!",
   "This isn't the good flavor!",
   "I REFUSE this meal!",
   "The bath! The HORROR!",
   "I'm wet! I'm DOOMED!",
   "Save me from the water!",
   "Thunder is ANGRY again!",
   "The doorbell! RUN!",
   "Strangers in MY house!",
   "Hide me under the bed!",
   "My tail got stepped ON!",
   "You sat in MY spot!",
   "Why is the door CLOSED?!",
   "What's behind the dooor?",
   "Nobody loves meee!",
   "I'm soooo boooored.",
   "Play with me NOW!",
   "Throw the mouse agaaain!",
   "The string is ALIVE!",
   "Look at meee, please!",
   "Put the phone DOWN!",
   "Wake uuup, it's breakfast!",
   "It's been 5 MINUTES!",
   "Dinner is two minutes late!",
   "I heard the can opener!",
   "The fridge opened! For me?",
   "Snaaacks, I neeed snacks!",
   "Treeeats or I scream.",
   "I will knock this OFF.",
   "Watch me push it...",
   "Oops, it fell! Tragic.",
   "Gravity is so DRAMATIC.",
   "The cucumber! RUN!",
   "I see something you don't!",
   "I am a MIGHTY hunter!",
   "Fear me, tiny mousey!",
   "Bow before your QUEEN!",
   "This house is MY kingdom!",
   "Worship me, peasant!",
   "Hug me! No, wait, stop!",
   "I changed my miiind!",
   "In! Out! In! OUT!",
   "The litter box is DIRTY!",
   "Clean my box, servant!",
   "Is that ANOTHER cat?!",
   "The mirror cat is BACK!",
   "The car ride is FOREVER!",
   "Are we there yeeet?",
   "I'm too pretty for this.",
   "My whiskers touched the bowl!",
   "Too cold! Blanket, PLEASE!",
   "Move over, bed hog!",
   "You moved in your SLEEP!",
   "Stop the singing, PLEASE!",
   "The dryer stopped! Tragic!",
   "I lost my toy... again.",
   "It's under the COUCH!",
   "Heeelp, I'm stuck up here!",
   "The curtain was a MISTAKE!",
   "Why do you work?!",
   "Quit your job. Stay home.",
   "Your keyboard needs MEEE!",
   "Scratch there! No, THERE!",
   "Who cut my claws?!",
   "My nemesis, the broom!",
   "Adore me more, pleeease!",
   "So hungry... so weak...",
   "Goodbye, cruel world.",
   "Farewell, sweet kibble.",
   "Remember me fondly...",
   "Nobody feeds me EVER!",
   "The water bowl is WARM!"
  ]
 }
};
